// ── Guide Data: 250 Countries ──────────────────────
// Parsed from flag_country_guide.md + verification_notes.md
const GUIDE_DATA = [
  { num: 1, code: "AD", emoji: "🇦🇩", name: "アンドラ", nameEn: "Andorra", status: "dejure",
    overview: "ピレネー山脈のフランス・スペイン間に位置する小国。共同大公制を採用し、観光とタックスヘイブンで知られる。",
    colorRules: "Blue 072 C・Yellow・Red 199 C。1999年政府規定により帯の比率は均等ではなく8:8:9と定められている。",
    trivia: "世界で唯一、2人の外国元首（仏大統領と西ウルヘル司教）が共同元首を務める国。紋章に4つの紋が配される。" },
  { num: 2, code: "AE", emoji: "🇦🇪", name: "アラブ首長国連邦", nameEn: "United Arab Emirates", status: "dejure",
    overview: "ペルシャ湾岸の7首長国からなる連邦国家。石油資源で急速に発展し、ドバイは国際的なハブ都市として繁栄する。",
    colorRules: "Red 186 C・Green 348 C。UAE政府ビジュアルアイデンティティガイドラインにより公式Pantone/CMYKが規定。",
    trivia: "4色（赤緑白黒）は汎アラブ色で、アッバース朝・ウマイヤ朝・ファーティマ朝・ハーシム家を象徴している。" },
  { num: 3, code: "AF", emoji: "🇦🇫", name: "アフガニスタン", nameEn: "Afghanistan", status: "defacto",
    overview: "中央アジアの内陸国。歴史的にシルクロードの要衝。2021年の政変でタリバンが実効支配するが国連は三色旗を維持。",
    colorRules: "Black 6 C・Red 485 C・Green 356 C。国際認識に従い三色旗で記述。タリバンの白旗は注記扱いとされる。",
    trivia: "20世紀に世界最多の約25回も国旗デザインを変更した国。現在も事実上の旗と法的な旗が併存する異例の状態。" },
  { num: 4, code: "AG", emoji: "🇦🇬", name: "アンティグア・バーブーダ", nameEn: "Antigua and Barbuda", status: "defacto",
    overview: "カリブ海東部の島国。2島と小島で構成される。1981年英国から独立。観光業とオフショア金融が主要産業。",
    colorRules: "Red 032 C等を使用。政府による明確なPantone指定の法律は存在せず、国際的な旗章学の標準近似値を採用。",
    trivia: "旗の上部のV字型は勝利を、太陽は新時代の夜明けを象徴。青はカリブ海、黒はアフリカの遺産を表している。" },
  { num: 5, code: "AI", emoji: "🇦🇮", name: "アンギラ", nameEn: "Anguilla", status: "defacto",
    overview: "カリブ海北東部のイギリス海外領土。珊瑚礁に囲まれた平坦な島で、高級リゾート地として知られる。",
    colorRules: "Blue 281 C（英ブルー・エンサイン標準）・Orange 150 C（イルカ紋章）。英国海外領土の規定に従う。",
    trivia: "紋章に描かれた3匹のイルカは島民の忍耐と友情を象徴。1967年に革命を起こし英国直轄統治に戻った珍しい歴史。" },
  { num: 6, code: "AL", emoji: "🇦🇱", name: "アルバニア", nameEn: "Albania", status: "dejure",
    overview: "バルカン半島南西部の国。アドリア海に面し、古代イリュリアの歴史を持つ。1990年代に民主化へ移行。",
    colorRules: "Red CMYK 0-100-100-0・Black CMYK 0-0-0-100。2002年法律第8926号で厳密に規定。縦横比は5:7。",
    trivia: "国旗の双頭の鷲は15世紀の英雄スカンデルベグに由来。「鷲の国」を意味する国名Shqipëriaとも関連する。" },
  { num: 7, code: "AM", emoji: "🇦🇲", name: "アルメニア", nameEn: "Armenia", status: "dejure",
    overview: "コーカサス地方の内陸国。世界初のキリスト教国家（301年）。アララト山を民族の象徴とする。",
    colorRules: "Red 485 C・Blue 286 C・Orange 1235 C。SARM（国立標準化機構）2012年の公式指定に完全準拠。",
    trivia: "赤は高原と独立の血、青はアルメニアの澄んだ空、橙はアルメニア人の勤勉さと創造性を象徴するとされる。" },
  { num: 8, code: "AO", emoji: "🇦🇴", name: "アンゴラ", nameEn: "Angola", status: "defacto",
    overview: "アフリカ南西部の国。1975年ポルトガルから独立。石油・ダイヤモンド資源に恵まれるが内戦の長い歴史を持つ。",
    colorRules: "Red 186 C等。憲法で色は定められているが公布されたPantone番号の法律は存在せず、標準近似値を使用。",
    trivia: "旗の中央にある鎌と歯車は労働者階級を、星は国際主義と進歩を象徴。マチェーテ（山刀）は農業を表す。" },
  { num: 9, code: "AQ", emoji: "🇦🇶", name: "南極", nameEn: "Antarctica", status: "defacto",
    overview: "主権国家ではない大陸。南極条約により科学研究のために国際管理される。30以上の国が観測基地を運営。",
    colorRules: "Navy Blue 2767 C・White 11-0601 TCX。「True South」旗の仕様を採用。比率は3:5。",
    trivia: "True South旗は2018年に提案され各国プログラムで広く採用。暗藍は極夜、白は氷と雪を表す。" },
  { num: 10, code: "AR", emoji: "🇦🇷", name: "アルゼンチン", nameEn: "Argentina", status: "dejure",
    overview: "南米第2の大国。パンパ（大草原）と多様な地形を擁する。タンゴ、サッカー、ワインで世界的に有名。",
    colorRules: "Sky Blue 284 C等。2010年大統領令でTC織物規格を定義。印刷用にはPantone Coated値を併用する。",
    trivia: "旗中央の「五月の太陽」はインカの太陽神インティに由来し、五月革命時に雲間から太陽が現れた伝説を表す。" },
  { num: 11, code: "AS", emoji: "🇦🇸", name: "アメリカ領サモア", nameEn: "American Samoa", status: "defacto",
    overview: "南太平洋のアメリカ非自治的未編入地域。ポリネシア文化が根強く、ツナ缶詰工場が経済の柱。",
    colorRules: "Blue 281 C・Red 032 C。ロンドン2012オリンピックマニュアル値を採用。現地政府の法定コードはなし。",
    trivia: "旗に描かれた白頭鷲が持つウォーメイスと扇は、サモアの首長の権威と知恵のシンボル。" },
  { num: 12, code: "AT", emoji: "🇦🇹", name: "オーストリア", nameEn: "Austria", status: "defacto",
    overview: "中央ヨーロッパの内陸国。アルプスの美しい山岳地帯を持ち、音楽の都ウィーンを首都とする。",
    colorRules: "Red 186 C・White。連邦法で単一のPantone指定はないが、186 Cが標準として広く受け入れられている。",
    trivia: "世界最古の国旗の一つ。1191年のアッコン包囲戦でレオポルト5世の血まみれの白衣に赤帯が残った伝説に由来。" },
  { num: 13, code: "AU", emoji: "🇦🇺", name: "オーストラリア", nameEn: "Australia", status: "dejure",
    overview: "オセアニア最大の国。大陸全体を占め、多文化社会を形成。固有種の動植物が多い。",
    colorRules: "Blue 280 C・Red 185 C。首相内閣省（PM&C）が公式Pantone指定を発行。法的に明確な根拠あり。",
    trivia: "南十字星とコモンウェルス・スターが配される。7つの角を持つ星は6州と1準州を統合的に表現。" },
  { num: 14, code: "AW", emoji: "🇦🇼", name: "アルバ", nameEn: "Aruba", status: "dejure",
    overview: "カリブ海南部のオランダ王国構成国。乾燥した島。観光とアロエ製品で有名。",
    colorRules: "Larkspur Blue 279 C・Bunting Yellow 109 C・Red 032 C。国家旗章法で厳格にPantone値が法定。",
    trivia: "赤い四芒星は島の4つの主要言語と4大陸からの移民を象徴。黄色い帯は金と観光の2つの主要産業を表す。" },
  { num: 15, code: "AX", emoji: "🇦🇽", name: "オーランド諸島", nameEn: "Åland Islands", status: "dejure",
    overview: "バルト海のフィンランド自治領。スウェーデン語が公用語。6500以上の島で構成。",
    colorRules: "Blue 2945 C・Yellow 116 C・Red 186 C。2004年第15号条例で極めて厳密にPantone/CMYKが制定。",
    trivia: "スウェーデン国旗の青黄にフィンランドの赤を加えた北欧十字の意匠。独特な比率17:26を採用する。" },
  { num: 16, code: "AZ", emoji: "🇦🇿", name: "アゼルバイジャン", nameEn: "Azerbaijan", status: "dejure",
    overview: "コーカサス東部の国。カスピ海に面し、石油・天然ガスの豊富な資源国。「火の国」の異名を持つ。",
    colorRules: "Blue 306 C・Red 032 C・Green 362 C。2013年国家象徴法改正で厳密なPantone指定がなされた。",
    trivia: "三日月と八芒星はイスラム教と8つのテュルク系民族を象徴。青はテュルクの遺産、緑はイスラムを表す。" },
  { num: 17, code: "BA", emoji: "🇧🇦", name: "ボスニア・ヘルツェゴビナ", nameEn: "Bosnia and Herzegovina", status: "defacto",
    overview: "バルカン半島中部の国。1990年代の民族紛争を経て3民族の連邦制を採る。",
    colorRules: "Blue 294 C・Yellow 116 C。欧州評議会旗の色に合致させる意図で設計された。",
    trivia: "デイトン合意後の1998年に制定。三角形と星は欧州を象徴するEU旗へのオマージュ。" },
  { num: 18, code: "BB", emoji: "🇧🇧", name: "バルバドス", nameEn: "Barbados", status: "defacto",
    overview: "カリブ海最東端の島国。1966年英国から独立。ラム酒発祥の地とされ、2021年に共和制へ移行。",
    colorRules: "Blue 280 C・Gold 123 C。制定時はイギリス標準規格で定義され、現代のPantone近似値に変換。",
    trivia: "旗中央の三叉鉾の頭部はネプチューンの武器。柄がないのは植民地支配からの断絶を象徴する独自の意匠。" },
  { num: 19, code: "BD", emoji: "🇧🇩", name: "バングラデシュ", nameEn: "Bangladesh", status: "defacto",
    overview: "南アジアのベンガル湾に面する国。世界有数の人口密度。繊維産業で経済成長を遂げている。",
    colorRules: "Green 342 C・Red 485 C。赤い円は意図的に旗竿側にオフセットされている特殊構造。",
    trivia: "日の丸と類似する赤い円の旗。竿に掲げた時に円が中央に見えるよう、ホイスト側に寄せてある。" },
  { num: 20, code: "BE", emoji: "🇧🇪", name: "ベルギー", nameEn: "Belgium", status: "dejure",
    overview: "西ヨーロッパの連邦国家。3言語共同体。EUとNATOの本部が置かれるブリュッセルが首都。",
    colorRules: "Yellow 115 C・Red 032 C。公式プロトコルガイドで厳格に規定。法的な比率は13:15。",
    trivia: "比率13:15のためほぼ正方形に近い珍しい旗。色の由来はブラバント公国の紋章に遡る。" },
  { num: 21, code: "BF", emoji: "🇧🇫", name: "ブルキナファソ", nameEn: "Burkina Faso", status: "defacto",
    overview: "西アフリカの内陸国。1984年にオートボルタから改称。「高潔な人々の祖国」を意味する。",
    colorRules: "Red 032 C・Yellow 116 C・Green 355 C。憲法に厳密な指定はなく、旗章学の標準近似値を採用。",
    trivia: "1984年のサンカラ革命で旗を刷新。赤は革命、緑は農業の豊かさ、黄色い星は革命の道しるべ。" },
  { num: 22, code: "BG", emoji: "🇧🇬", name: "ブルガリア", nameEn: "Bulgaria", status: "dejure",
    overview: "バルカン半島東部の国。黒海に面し、ヨーグルトとバラの精油で有名。キリル文字の発祥地。",
    colorRules: "Green 347 U・Red 032 U。国家法でPantone Textile値が厳密に定められている。",
    trivia: "EU加盟国で唯一キリル文字を使用する国。白は平和、緑は農業、赤は独立のための血を象徴する。" },
  { num: 23, code: "BH", emoji: "🇧🇭", name: "バーレーン", nameEn: "Bahrain", status: "dejure",
    overview: "ペルシャ湾の島国。約40の島からなる小さな王国。金融センターとして発展。",
    colorRules: "Red 485 C。政府発行の公式ガイドラインで明確に指定。5つのジグザグ三角形が配される。",
    trivia: "5つの鋸歯はイスラム教の五行を象徴。2002年以前は8つだったが国旗変更時に5つに改められた。" },
  { num: 24, code: "BI", emoji: "🇧🇮", name: "ブルンジ", nameEn: "Burundi", status: "defacto",
    overview: "アフリカ大湖地域の内陸国。タンガニーカ湖に面する。コーヒーと茶が主要輸出品。",
    colorRules: "Red 186 C・Green 361 C。政府文書にPantone番号は存在しない。オリンピック共通規格を採用。",
    trivia: "白いX字帯で4つの三角に分割。中央の白円盤に3つの赤い六芒星（フツ・ツチ・トゥワ族を象徴）。" },
  { num: 25, code: "BJ", emoji: "🇧🇯", name: "ベナン", nameEn: "Benin", status: "defacto",
    overview: "西アフリカの小国。旧ダホメ王国の歴史を持つ。ブードゥー教の発祥地とされる。",
    colorRules: "Green 355 C・Yellow 109 C・Red 032 C。政府令でPantoneなし。国際規格の標準値を採用。",
    trivia: "緑は希望と再生、黄は大地の富、赤は祖先の勇気を象徴。緑はホイスト側の縦帯で配置される。" },
  { num: 26, code: "BL", emoji: "🇧🇱", name: "サン・バルテルミー", nameEn: "Saint Barthélemy", status: "dejure",
    overview: "カリブ海のフランス海外集団。高級リゾート地として世界のセレブリティに人気。面積は約25km²。",
    colorRules: "法定旗はフランス三色旗（NFX 08-002）。独自の紋章旗は非公式でPantone指定なし。",
    trivia: "島名はコロンブスが弟バルトロメオにちなんで命名。紋章にはマルタ十字とペリカンが描かれる。" },
  { num: 27, code: "BM", emoji: "🇧🇲", name: "バミューダ", nameEn: "Bermuda", status: "defacto",
    overview: "北大西洋のイギリス海外領土。約180の島で構成。オフショア金融と保険業が経済の柱。",
    colorRules: "Red 032 C・Dark Blue 281 C。英国レッド・エンサインに基づく。固有のPantone法令なし。",
    trivia: "英海外領で珍しくレッド・エンサインを使用。紋章にはSea Venture号の難破が描かれ建国の起源を示す。" },
  { num: 28, code: "BN", emoji: "🇧🇳", name: "ブルネイ", nameEn: "Brunei", status: "defacto",
    overview: "ボルネオ島北西部の石油・天然ガス豊かな小国。スルタンが統治するイスラム教絶対君主制国家。",
    colorRules: "Yellow 102 C・Red 032 C。政府の公式カラーテーブルは非公開。国際的近似値を採用。",
    trivia: "黄色地は国王の絶対権威の色。白黒の斜帯と赤い国章（三日月・傘・旗・翼手）を配する。" },
  { num: 29, code: "BO", emoji: "🇧🇴", name: "ボリビア", nameEn: "Bolivia", status: "dejure",
    overview: "南米の内陸国。世界最高地の首都ラパスを持つ。チチカカ湖やウユニ塩湖で知られる。",
    colorRules: "Red 485 C・Yellow Process Yellow C・Green 356 C。2004年最高法令第27630号でPantone公式指定。",
    trivia: "先住民のウィパラ旗も同等に公式使用される。赤は勇敢な兵士の血、黄は資源の豊さ、緑は大地。" },
  { num: 30, code: "BQ", emoji: "🇧🇶", name: "オランダ領カリブ", nameEn: "Caribbean Netherlands", status: "dejure",
    overview: "ボネール・シント・ユースタティウス・サバの3島のオランダ特別自治体。ダイビングの聖地。",
    colorRules: "Bright Vermilion・Cobalt Blue。NEN 3055に基づくCIE色空間で厳密に定義。",
    trivia: "この総称に対する固有の旗はなく、オランダ国旗が公式旗。各島にそれぞれ独自の島旗が存在。" },
  { num: 31, code: "BR", emoji: "🇧🇷", name: "ブラジル", nameEn: "Brazil", status: "defacto",
    overview: "南米最大の国。ポルトガル語圏最大の国家。アマゾン熱帯雨林、サンバ、サッカーで著名。",
    colorRules: "Green 355 C・Yellow C・Blue 280 C。法律で色は定められるがPantone指定はなし。",
    trivia: "青い天球に白い星27個と「ORDEM E PROGRESSO」の帯。星は独立時の夜空を再現している。" },
  { num: 32, code: "BS", emoji: "🇧🇸", name: "バハマ", nameEn: "Bahamas", status: "dejure",
    overview: "カリブ海北部の島国。約700の島と2400の岩礁からなる。パラダイス島のリゾートが有名。",
    colorRules: "Aquamarine 3145 C・Gold 123 C・Black。バハマ政府が明確に公式Pantone値を指定。",
    trivia: "黒い正三角形は国民の団結と決意、アクアマリンの帯は海、金の帯は太陽と砂浜を象徴する。" },
  { num: 33, code: "BT", emoji: "🇧🇹", name: "ブータン", nameEn: "Bhutan", status: "defacto",
    overview: "ヒマラヤ山脈東部の仏教王国。「国民総幸福量」（GNH）で知られる環境保護に熱心な国。",
    colorRules: "Yellow 116 C・Orange 165 C。政府文書でRALカラー指定もあるが国際的にはPantone Coatedを使用。",
    trivia: "国名ドゥク・ユル（雷龍の国）に由来する白い龍（ドゥク）が中央に描かれる。宝石は国の富の象徴。" },
  { num: 34, code: "BV", emoji: "🇧🇻", name: "ブーベ島", nameEn: "Bouvet Island", status: "dejure",
    overview: "南大西洋のノルウェー属領の無人火山島。世界で最も孤立した島の一つで、93%が氷河に覆われる。",
    colorRules: "Red 200 C・Blue 281 C。ノルウェー外務省の2021年公式ガイドライン準拠。ノルウェー国旗を使用。",
    trivia: "地球上で最も孤立した島の一つ。最寄りの有人地まで約1600km離れている。" },
  { num: 35, code: "BW", emoji: "🇧🇼", name: "ボツワナ", nameEn: "Botswana", status: "defacto",
    overview: "南部アフリカの内陸国。ダイヤモンド産出国として急速に経済発展。カラハリ砂漠が有名。",
    colorRules: "Blue 277 C。Emblems Actでは「Azure Blue」とのみ記載。ロンドンオリンピック標準の値を採用。",
    trivia: "淡い青は雨（プラ）を表し通貨名にもなっている。黒白ストライプはゼブラと人種の調和を象徴。" },
  { num: 36, code: "BY", emoji: "🇧🇾", name: "ベラルーシ", nameEn: "Belarus", status: "defacto",
    overview: "東ヨーロッパの内陸国。旧ソ連構成国。ミンスクが首都。",
    colorRules: "Red 1795 C・Green 355 C。大統領令で意匠は定義されるがPantone指定なし。標準近似値を使用。",
    trivia: "ホイスト側の赤白の装飾模様はルーシヌィク（伝統刺繍タオル）を再現。ソ連時代デザインの復刻版。" },
  { num: 37, code: "BZ", emoji: "🇧🇿", name: "ベリーズ", nameEn: "Belize", status: "dejure",
    overview: "中米のカリブ海沿岸国。英連邦の一員で英語が公用語。世界第2位のサンゴ礁がある。",
    colorRules: "Dark Blue 2738 C・Red 485 C。National Celebrations Commission（2019年）が公式に制定。",
    trivia: "世界で最も複雑な国旗の一つ。50色以上使用する紋章には木こり、帆船、道具、マホガニーの木を描く。" },
  { num: 38, code: "CA", emoji: "🇨🇦", name: "カナダ", nameEn: "Canada", status: "dejure",
    overview: "世界第2位の面積を持つ北米の国。英仏二言語の多文化社会。豊かな自然資源と高い生活水準。",
    colorRules: "Red 032 C（CMYK: 0,100,100,0）。Federal Identity Programで厳密に法定規定のDe jure指定。",
    trivia: "メープルリーフ旗の11の頂点は風洞実験で風になびいても視認性が最も高い形状として選ばれた。" },
  { num: 39, code: "CC", emoji: "🇨🇨", name: "ココス（キーリング）諸島", nameEn: "Cocos Islands", status: "defacto",
    overview: "インド洋のオーストラリア領。2つの環礁からなる27の島。人口は約600人。",
    colorRules: "Green 356 C・Yellow 116 C・Brown 1535 C。公式Pantone規定なし。推奨カラーを採用。",
    trivia: "2004年に高校生のデザインコンペから採用された旗。緑地にヤシの木、三日月、南十字星を描く。" },
  { num: 40, code: "CD", emoji: "🇨🇩", name: "コンゴ民主共和国", nameEn: "DR Congo", status: "defacto",
    overview: "アフリカ大陸第2位の面積。旧ザイール。コバルト・コルタン等の鉱物資源が豊富。",
    colorRules: "Process Blue C・Yellow 109 C・Red 032 C。Pantone指定はなく標準仕様を採用。",
    trivia: "スカイブルーは平和、赤い帯は殉教者の血、黄色い星は国の輝く未来。2006年新憲法で現行デザインに復帰。" },
  { num: 41, code: "CF", emoji: "🇨🇫", name: "中央アフリカ共和国", nameEn: "Central African Republic", status: "defacto",
    overview: "アフリカの地理的中心に位置する内陸国。ダイヤモンドが主要輸出品。首都はバンギ。",
    colorRules: "Blue 287 C・Green 355 C・Yellow 116 C・Red 186 C。法的拘束力なし。オリンピックマニュアル準拠。",
    trivia: "世界唯一、汎アフリカ色と旧宗主国フランスの三色旗を一つに融合させた国旗デザイン。" },
  { num: 42, code: "CG", emoji: "🇨🇬", name: "コンゴ共和国", nameEn: "Republic of the Congo", status: "defacto",
    overview: "中部アフリカの国。コンゴ川を挟んでコンゴ民主共和国と隣接。首都はブラザビル。",
    colorRules: "Green 355 C・Yellow 109 C・Red 032 C。憲法で色は定められるが具体的Pantone指定なし。",
    trivia: "対角配置の三色旗が特徴的。緑は農業と希望、黄は友好と誠実さ、赤は独立闘争を象徴する。" },
  { num: 43, code: "CH", emoji: "🇨🇭", name: "スイス", nameEn: "Switzerland", status: "dejure", tags: ["square"],
    overview: "中央ヨーロッパの永世中立国。4つの公用語を持ち、金融、時計、チョコレートで著名。",
    colorRules: "Red 485 C（CMYK: 0,100,100,0）。2013年連邦法SR 232.21の付属書で厳格にPantoneが法制化。",
    trivia: "バチカンと並ぶ世界で2つの正方形国旗。赤十字旗はこの旗の色反転デザインに由来。" },
  { num: 44, code: "CI", emoji: "🇨🇮", name: "コートジボワール", nameEn: "Côte d'Ivoire", status: "defacto",
    overview: "西アフリカの国。世界最大のカカオ生産国。フランス語圏で経済的中心地のアビジャンが栄える。",
    colorRules: "Orange 151 C・Green 347 C。法律上のカラーコード言及なし。Album des Pavillonsの標準値を使用。",
    trivia: "アイルランド国旗を反転させたような配色だが偶然。橙はサバンナ、白は平和、緑は森林を表す。" },
  { num: 45, code: "CK", emoji: "🇨🇰", name: "クック諸島", nameEn: "Cook Islands", status: "defacto",
    overview: "南太平洋のニュージーランド自由連合国。15の島からなる。観光業と真珠養殖が盛ん。",
    colorRules: "Blue 281 C・Red 032 C。NZ・英国の標準に準拠した国際的使用標準Pantone値を使用。",
    trivia: "ブルー・エンサインに15の白い星を円形に配置。15の星は15の島の統一と信仰を象徴する。" },
  { num: 46, code: "CL", emoji: "🇨🇱", name: "チリ", nameEn: "Chile", status: "defacto",
    overview: "南米西岸の南北に細長い国。アンデス山脈からアタカマ砂漠まで多様な地形。銅の世界最大輸出国。",
    colorRules: "Blue 286 C・Red 485 C。旗の使用は規定で定められるが正確なPantone色規定なし。",
    trivia: "テキサス州旗と酷似するがチリ国旗の方が約2年早い1817年に制定。白い星は進歩と名誉を象徴。" },
  { num: 47, code: "CM", emoji: "🇨🇲", name: "カメルーン", nameEn: "Cameroon", status: "defacto",
    overview: "中西アフリカの二言語国家。「アフリカのミニチュア」と呼ばれる多様な地形と文化を有する。",
    colorRules: "Green 355 C・Red 032 C・Yellow 109 C。憲法で意匠は定義されるがカラーコード指定なし。",
    trivia: "中央の黄色い星は統一のシンボルで「統一の星」と呼ばれる。フランス三色旗がモデル。" },
  { num: 48, code: "CN", emoji: "🇨🇳", name: "中国", nameEn: "China", status: "dejure",
    overview: "東アジアの国。5000年の歴史と世界第2位のGDPを誇る社会主義国家。世界最大の人口。",
    colorRules: "Red 186 C・Yellow 116 C。法定標準GB 12983-2004でCIE色空間により厳密に規定。",
    trivia: "大きい星は共産党、4つの小星は労働者・農民・知識人・民族資本家の4階級を象徴。通称「五星紅旗」。" },
  { num: 49, code: "CO", emoji: "🇨🇴", name: "コロンビア", nameEn: "Colombia", status: "defacto",
    overview: "南米北西部の国。太平洋とカリブ海の両方に面する。コーヒー・エメラルドの産地として有名。",
    colorRules: "Yellow 116 C・Blue 287 C・Red 186 C。明確な色指定法律なし。オリンピック旗マニュアル標準値。",
    trivia: "黄帯が旗の半分を占める特殊な比率（2:1:1）。黄は金と太陽、青は二つの海、赤は独立戦争の血。" },
  { num: 50, code: "CR", emoji: "🇨🇷", name: "コスタリカ", nameEn: "Costa Rica", status: "defacto",
    overview: "中米の共和国。1948年に軍隊を廃止した平和国家。エコツーリズムの先進国。",
    colorRules: "Blue 281 C・Red 032 C。法律で意匠は定義されるがPantone指定なし。標準値を使用。",
    trivia: "中米5カ国で唯一、紋章に武器が描かれない。紋章ありの「国旗」と紋章なしの「市民旗」が存在。" },
  { num: 51, code: "CU", emoji: "🇨🇺", name: "キューバ", nameEn: "Cuba", status: "defacto",
    overview: "カリブ海最大の島国。社会主義国家。葉巻、ラム酒、音楽で知られる。",
    colorRules: "Red 485 C・Blue 301 C。厳密なPantone指定はなし。国際的に確立した標準近似値を記録。",
    trivia: "旗は1849年にニューヨークで亡命キューバ人がデザイン。白い孤星は独立の象徴。" },
  { num: 52, code: "CV", emoji: "🇨🇻", name: "カーボベルデ", nameEn: "Cape Verde", status: "dejure",
    overview: "西アフリカ沖の大西洋上の島国。10の火山島で構成。音楽ジャンル「モルナ」の発祥地。",
    colorRules: "Blue 287 C・Red 186 C・Yellow 116 C。2009年政府マニュアルで公式にDe jure指定。",
    trivia: "10の黄色い星は10の主要島を円形に表す。青は大西洋を、「緑の岬」が国名の由来。" },
  { num: 53, code: "CW", emoji: "🇨🇼", name: "キュラソー", nameEn: "Curaçao", status: "defacto",
    overview: "カリブ海南部のオランダ王国構成国。カラフルな建築が世界遺産。キュラソー酒発祥の地。",
    colorRules: "Blue 280 C・Yellow 102 C。法的なPantone指定はなく旗章学の標準値に正規化。",
    trivia: "2つの白星はキュラソーとクレイン・キュラソー（小キュラソー島）を象徴する。" },
  { num: 54, code: "CX", emoji: "🇨🇽", name: "クリスマス島", nameEn: "Christmas Island", status: "defacto",
    overview: "インド洋のオーストラリア領。毎年のアカガニ大移動で世界的に有名。多文化社会が特徴。",
    colorRules: "Dark Blue C・Green 7731 C・Yellow 136 C。2002年正式採用だがPantone指定なし。",
    trivia: "緑と青の対角分割に黄色い地図シルエットと南十字星。金色のアカガニも描かれている。" },
  { num: 55, code: "CY", emoji: "🇨🇾", name: "キプロス", nameEn: "Cyprus", status: "dejure",
    overview: "地中海東部の島国。ギリシャ系とトルコ系の2コミュニティ。EU加盟国。",
    colorRules: "Copper 1385 C・Olive Green 574 C。2006年政府規定に基づきDe jure指定。銅色と緑が公式色名。",
    trivia: "世界で唯一、國の地図の輪郭を描いた国旗の一つ。銅色は3000年以上の銅の産地に由来。" },
  { num: 56, code: "CZ", emoji: "🇨🇿", name: "チェコ", nameEn: "Czechia", status: "defacto",
    overview: "中央ヨーロッパの内陸国。ビール消費量世界一。プラハの美しい街並みが魅力。",
    colorRules: "Blue 287 C・Red 192 C。法律で色は定義されるが技術的なPantone法的規定なし。",
    trivia: "1920年にチェコスロバキアとして制定。分離後もスロバキアが新旗を制定したためチェコが旧旗を継続。" },
  { num: 57, code: "DE", emoji: "🇩🇪", name: "ドイツ", nameEn: "Germany", status: "dejure",
    overview: "ヨーロッパ最大の経済大国。EU最大の人口と工業力。自動車産業・ビール文化で著名。",
    colorRules: "Black C・Red 485 C・Gold 7405 C。連邦政府コーポレートデザイン規格に基づくDe jure指定。",
    trivia: "黒赤金は1813年の義勇軍リュッツォウの制服色に由来。「金」であり「黄」ではないのが正式。" },
  { num: 58, code: "DJ", emoji: "🇩🇯", name: "ジブチ", nameEn: "Djibouti", status: "defacto",
    overview: "アフリカの角に位置する小国。戦略的要衝。仏・米・日・中の軍事基地がある。",
    colorRules: "Light Blue 292 C・Green 361 C・Red 032 C。法的なPantone指定なし。汎用近似標準値を採用。",
    trivia: "水色はイッサ族と空海、緑はアファル族と大地、赤い五芒星はイッサ・アファルの統一を象徴。" },
  { num: 59, code: "DK", emoji: "🇩🇰", name: "デンマーク", nameEn: "Denmark", status: "dejure",
    overview: "北ヨーロッパのスカンジナビア国家。世界最古の王室を持つ幸福度の高い国。",
    colorRules: "Red 186 C。DS 359「ダンネブローの赤」に基づく事実上の国家標準。De jure指定。",
    trivia: "ダンネブロー（デンマークの布）は1219年から使用される世界最古の現役国旗。天から降ってきたとの伝説。" },
  { num: 60, code: "DM", emoji: "🇩🇲", name: "ドミニカ国", nameEn: "Dominica", status: "defacto", tags: ["unique"],
    overview: "カリブ海の火山島国。「カリブ海の自然の島」と呼ばれ熱帯雨林に覆われる。",
    colorRules: "Green 347 C・Yellow 116 C・Red 185 C・Purple 254 C。法的な政府規定なし。",
    trivia: "国旗に紫色を使用する世界で2カ国のうちの1つ（もう1国はニカラグア）。中央にシッセロウインコ。" },
  { num: 61, code: "DO", emoji: "🇩🇴", name: "ドミニカ共和国", nameEn: "Dominican Republic", status: "defacto",
    overview: "カリブ海のイスパニョーラ島東部を占める国。野球大国で多くのMLB選手を輩出。",
    colorRules: "Blue 294 C・Red 186 C。憲法で色名が定義されるが数値規定なし。",
    trivia: "世界で唯一、聖書が国旗に組み込まれている国。中央の紋章に開かれた聖書（ヨハネ8:32）がある。" },
  { num: 62, code: "DZ", emoji: "🇩🇿", name: "アルジェリア", nameEn: "Algeria", status: "defacto",
    overview: "アフリカ最大の面積の北アフリカの国。サハラ砂漠が約80%を占める。石油天然ガスの産出国。",
    colorRules: "Green 356 C・Red 186 C。政府の厳密なPantone指定なし。旗章学標準に正規化。",
    trivia: "緑はイスラム教、白は純潔を象徴。赤い三日月と星はイスラム共通の意匠。1962年独立で正式制定。" },
  { num: 63, code: "EC", emoji: "🇪🇨", name: "エクアドル", nameEn: "Ecuador", status: "dejure",
    overview: "赤道直下の南米の国。アンデス、アマゾン、ガラパゴスと多様な生態系を持つ。",
    colorRules: "Yellow 109 C・Blue 285 C・Red 032 C。2009年にSENACOMがマニュアルでDe jure指定。",
    trivia: "コロンビア・ベネズエラと同系統の「大コロンビア」色の旗。紋章にコンドルとチンボラソ山を配する。" },
  { num: 64, code: "EE", emoji: "🇪🇪", name: "エストニア", nameEn: "Estonia", status: "dejure",
    overview: "バルト三国最北の国。世界最先端の電子政府を実現したIT立国。タリン旧市街は世界遺産。",
    colorRules: "Blue 285 C。2005年国旗法でPantone 285 Cと法的に明記されたDe jure指定。",
    trivia: "青は空と湖と忠誠、黒は祖国の大地と暗い過去、白は雪と純潔と未来。1881年に学生団体が初使用。" },
  { num: 65, code: "EG", emoji: "🇪🇬", name: "エジプト", nameEn: "Egypt", status: "defacto",
    overview: "北アフリカ・中東にまたがる国。ナイル川流域の古代文明の発祥地。ピラミッドで有名。",
    colorRules: "Red 186 C・Gold 116 C。法律で色と紋章は定められるがPantone数値規定なし。",
    trivia: "中央の金色のサラディンの鷲は12世紀のスルタンに由来する汎アラブ象徴。赤は革命前の犠牲者の血。" },
  { num: 66, code: "EH", emoji: "🇪🇭", name: "西サハラ", nameEn: "Western Sahara", status: "defacto",
    overview: "北アフリカの係争地域。モロッコが大部分を実効支配し、ポリサリオ戦線が共和国を宣言。",
    colorRules: "Green 3546 C・Black 6 C・Red 7732 C。法的なPantone規定なし。汎アラブ色の標準近似値。",
    trivia: "汎アラブ色を使用した解放運動の旗。赤い三角と三日月・星はアラブの団結とイスラムを象徴する。" },
  { num: 67, code: "ER", emoji: "🇪🇷", name: "エリトリア", nameEn: "Eritrea", status: "defacto",
    overview: "アフリカの角に位置する紅海沿岸国。1993年にエチオピアから独立した若い国。",
    colorRules: "Green 361 C・Red 185 C・Blue 279 C・Gold 123 C。法的にPantone/CMYK値は未規定。",
    trivia: "赤い三角のオリーブ花輪はイタリア植民地時代からの伝統。30年の独立戦争の犠牲を赤が象徴。" },
  { num: 68, code: "ES", emoji: "🇪🇸", name: "スペイン", nameEn: "Spain", status: "dejure",
    overview: "イベリア半島の大部分を占める西ヨーロッパの国。闘牛、フラメンコ、パエリアで有名。",
    colorRules: "Red 032 C・Yellow 109 C。1981年王令でCIELAB色空間により厳密に法定。",
    trivia: "赤黄は1785年にカルロス3世が海上識別のために選んだ色。黄帯幅は赤帯の2倍。" },
  { num: 69, code: "ET", emoji: "🇪🇹", name: "エチオピア", nameEn: "Ethiopia", status: "defacto",
    overview: "アフリカの角の内陸国。一度も植民地化されなかったアフリカの独立の象徴。コーヒー発祥の地。",
    colorRules: "Green 347 C・Yellow C・Red 032 C・Blue 2728 C。Pantone法的規定なし。標準と一致。",
    trivia: "緑黄赤の配色は多くのアフリカ諸国に影響を与え「汎アフリカ色」の起源。植民地抵抗の象徴的な旗。" },
  { num: 70, code: "FI", emoji: "🇫🇮", name: "フィンランド", nameEn: "Finland", status: "dejure",
    overview: "北ヨーロッパの国。「千の湖の国」で約18万8千の湖がある。サウナ文化と教育水準で著名。",
    colorRules: "Blue 294 C。1993年政府決定でCIE色空間で法定。実用Pantone換算値として294 Cを適用。",
    trivia: "白は雪、青は湖と空を象徴する北欧十字旗。「青い十字旗」として国民に親しまれる。" },
  { num: 71, code: "FJ", emoji: "🇫🇯", name: "フィジー", nameEn: "Fiji", status: "defacto",
    overview: "南太平洋の島国。約330の島からなる。メラネシアとポリネシアの文化が融合。ラグビーで有名。",
    colorRules: "Light Blue 2915 C・Dark Blue 281 C・Red 186 C等。政府Pantone規定なし。",
    trivia: "紋章にサトウキビ・ヤシ・バナナ・ハトが描かれる。2015年に新旗の国民投票が計画されたが見送り。" },
  { num: 72, code: "FK", emoji: "🇫🇰", name: "フォークランド諸島", nameEn: "Falkland Islands", status: "defacto",
    overview: "南大西洋のイギリス海外領土。アルゼンチンが領有権を主張し1982年紛争が勃発。",
    colorRules: "Blue 281 C・Red 186 C。英標準エンサイン色を適用。固有のPantone法令なし。",
    trivia: "紋章に羊と帆船Desire号。人口の約6倍にあたる50万頭以上の羊が生息する島。" },
  { num: 73, code: "FM", emoji: "🇫🇲", name: "ミクロネシア連邦", nameEn: "Micronesia", status: "defacto",
    overview: "西太平洋の連邦国家。約600の島からなる4州で構成。アメリカとの自由連合協定で安保確保。",
    colorRules: "Blue 277 C。法律上「青地に白い4つの星」とのみ規定。国連旗の青に倣った色合い。",
    trivia: "4つの白い星はヤップ・チューク・ポンペイ・コスラエの4州を象徴。青は太平洋の広大な海を表す。" },
  { num: 74, code: "FO", emoji: "🇫🇴", name: "フェロー諸島", nameEn: "Faroe Islands", status: "dejure",
    overview: "北大西洋のデンマーク自治領。18の火山島で構成される。バイキングの末裔の島。",
    colorRules: "Red 032 C・Blue 300 C。北欧理事会とフェロー政府が公式にPantone値を指定。De jure。",
    trivia: "1919年に漁民が考案した北欧十字旗。ノルウェー十字旗の赤青を反転させた二重十字が特徴的。" },
  { num: 75, code: "FR", emoji: "🇫🇷", name: "フランス", nameEn: "France", status: "dejure",
    overview: "西ヨーロッパの共和国。世界最多の観光客を集める文化大国。ファッション・美食・ワインの国。",
    colorRules: "Blue 2738 C・Red 2347 C。Album des Pavillons 2023年版の最新公式値。旧072/485は旧値。",
    trivia: "トリコロールは1794年制定で世界中の三色旗の模範。2020年にマクロンが青を海軍色（濃紺）に戻した。" },
  { num: 76, code: "GA", emoji: "🇬🇦", name: "ガボン", nameEn: "Gabon", status: "defacto",
    overview: "中部アフリカの赤道直下の国。石油と森林資源に恵まれる。国土の80%が熱帯雨林。",
    colorRules: "Green 347 C・Yellow 116 C・Blue 285 C。Album des Pavillonsの値を優先。",
    trivia: "緑は森林、黄は赤道と太陽、青は大西洋。等幅の横三色帯というシンプルかつ美しいデザイン。" },
  { num: 77, code: "GB", emoji: "🇬🇧", name: "イギリス", nameEn: "United Kingdom", status: "defacto",
    overview: "北西ヨーロッパの島国。4カ国連合。産業革命の発祥地。世界的な影響力を持つ。",
    colorRules: "Blue 280 C・Red 186 C。Flag Institute推奨値。法的に色を義務付ける規格は存在しない。",
    trivia: "ユニオンジャックは3つの十字を重ねた旗。ウェールズの旗のデザインは含まれていない。" },
  { num: 78, code: "GD", emoji: "🇬🇩", name: "グレナダ", nameEn: "Grenada", status: "defacto",
    overview: "カリブ海南東部の島国。「スパイスの島」と呼ばれナツメグの世界最大産出国の一つ。",
    colorRules: "Red 032 C・Yellow 109 C・Green 355 C。Pantone/CMYKは未規定。旗章学標準を確認。",
    trivia: "左ホイスト側にナツメグが描かれる世界唯一の国旗。6外枠星+1中央星は7つの教区を象徴。" },
  { num: 79, code: "GE", emoji: "🇬🇪", name: "ジョージア", nameEn: "Georgia", status: "defacto",
    overview: "コーカサス南部の国。黒海に面し、ワイン発祥（8000年前）の地。独自のアルファベット。",
    colorRules: "Red 485 C。法律は構造を定義するが赤色のPantone番号は未法制化。485 Cが標準。",
    trivia: "2004年のバラ革命後に中世ジョージアの「五十字旗」を復活。4隅のボルニシ十字が特徴。" },
  { num: 80, code: "GF", emoji: "🇬🇫", name: "フランス領ギアナ", nameEn: "French Guiana", status: "dejure",
    overview: "南米北東部のフランス海外県。アマゾン熱帯雨林が90%以上。クールー宇宙センターの所在地。",
    colorRules: "Blue 2738 C・Red 2347 C。公式旗はフランス三色旗のみ。非公式旗にPantone指定なし。",
    trivia: "EU最大の面積を持つ「地域」。欧州宇宙機関のロケット打上げ基地がある赤道直下のフランス領。" },
  { num: 81, code: "GG", emoji: "🇬🇬", name: "ガーンジー", nameEn: "Guernsey", status: "defacto",
    overview: "イギリス海峡の王室属領。独自の議会と法制度を持つ金融センター。",
    colorRules: "Red（聖ジョージ十字）・Gold（ノルマン十字）。Pantone法定規定なし。比率3:5。",
    trivia: "1985年にイングランドと区別するため金色のノルマン十字を追加。征服王の紋章に由来。" },
  { num: 82, code: "GH", emoji: "🇬🇭", name: "ガーナ", nameEn: "Ghana", status: "defacto",
    overview: "西アフリカのギニア湾岸国。1957年にサハラ以南アフリカ初の独立国。金・カカオが主要資源。",
    colorRules: "Red 032 C・Gold 109 C・Green 355 C。技術的カラーコードは公布されていない。",
    trivia: "黒い星はアフリカ解放と統一のシンボルで、首都アクラのサッカースタジアムの名前にもなっている。" },
  { num: 83, code: "GI", emoji: "🇬🇮", name: "ジブラルタル", nameEn: "Gibraltar", status: "dejure",
    overview: "イベリア半島南端のイギリス海外領土。地中海の入口に位置する戦略的要衝。",
    colorRules: "Red 485 C・Amber 143 C・Black Process Black C。2003年300年記念事業でDe jure指定。",
    trivia: "紋章の三塔城とぶら下がる鍵は「地中海の鍵」の象徴。白地に赤下帯という珍しい旗形式。" },
  { num: 84, code: "GL", emoji: "🇬🇱", name: "グリーンランド", nameEn: "Greenland", status: "defacto",
    overview: "世界最大の島でデンマークの自治領。国土の約80%が氷床に覆われる。イヌイット文化が根強い。",
    colorRules: "Red 032 C・White。Album des Pavillonsに基づく。デンマーク国旗と同色の赤を使用。",
    trivia: "「エルファラソルプト（我らの旗）」。Thue Christiansenデザイン。白赤の半円は氷山と太陽を表す。" },
  { num: 85, code: "GM", emoji: "🇬🇲", name: "ガンビア", nameEn: "Gambia", status: "defacto",
    overview: "西アフリカのガンビア川沿いの細長い国。セネガルにほぼ囲まれている。落花生が主要産業。",
    colorRules: "Red 186 C・Blue 293 C・Green 361 C。Album des Pavillons 2023年版の最新値に更新。",
    trivia: "青はガンビア川（国の生命線）を象徴。ガンビア川のない国旗は考えられないほど重要な存在。" },
  { num: 86, code: "GN", emoji: "🇬🇳", name: "ギニア", nameEn: "Guinea", status: "defacto",
    overview: "西アフリカの大西洋岸国。世界最大級のボーキサイト埋蔵量。1958年にフランスから独立。",
    colorRules: "Red 032 C・Yellow 109 C・Green 355 C。憲法で色名のみ定義。北京2008マニュアル等で確認。",
    trivia: "フランス三色旗を元にしたパン・アフリカ色の縦三色旗。赤は犠牲の血、黄は太陽と鉱物、緑は植生。" },
  { num: 87, code: "GP", emoji: "🇬🇵", name: "グアドループ", nameEn: "Guadeloupe", status: "dejure",
    overview: "カリブ海のフランス海外県。蝶の形をした2つの主要島からなる。ラム酒・砂糖が名産物。",
    colorRules: "Blue 2738 C・Red 2347 C。フランス三色旗が唯一の公式旗。2023年版最新値に統一。",
    trivia: "フランスの正式なEU領域の一部。非公式旗にはサトウキビと太陽が描かれる。" },
  { num: 88, code: "GQ", emoji: "🇬🇶", name: "赤道ギニア", nameEn: "Equatorial Guinea", status: "defacto",
    overview: "中部アフリカ唯一のスペイン語圏国。石油発見で急速に経済発展した小国。",
    colorRules: "Green 347 C・Red 032 C・Blue 293 C。政府法定仕様なし。CRW Flags等旗章学DBに基づく。",
    trivia: "国章のシルクコットンの木はマドリード条約締結場所の象徴。格言「UNIDAD–PAZ–JUSTICIA」。" },
  { num: 89, code: "GR", emoji: "🇬🇷", name: "ギリシャ", nameEn: "Greece", status: "defacto",
    overview: "地中海東部のバルカン半島南端の国。西洋文明の発祥地で民主主義・哲学の起源。",
    colorRules: "Blue 286 C（Album des Pavillons準拠）。法律は「キアノス」と白のみ規定。定義なし。",
    trivia: "歴史的に青の濃淡が大きく変遷。9本の縞は「自由か死か（Ελευθερία ή θάνατος）」の9音節。" },
  { num: 90, code: "GS", emoji: "🇬🇸", name: "サウスジョージア・サウスサンドウィッチ諸島", nameEn: "South Georgia", status: "defacto",
    overview: "南大西洋のイギリス海外領土。亜南極の無人島群でペンギン・アザラシのコロニーが存在。",
    colorRules: "Blue 281 C・Red 186 C。英標準ブルー・エンサイン色。紋章は1992年王室令で授与。",
    trivia: "紋章にトーチを持つ金ライオン・オットセイ・マカロニペンギン・トナカイが描かれる。" },
  { num: 91, code: "GT", emoji: "🇬🇹", name: "グアテマラ", nameEn: "Guatemala", status: "defacto",
    overview: "中米最大の人口を持つ国。マヤ文明の中心地ティカル。コーヒー生産とテキスタイルで有名。",
    colorRules: "Sky Blue 299 C。法律上「空色」と定義。ISCC-NBS 177と紐づき299 Cが標準。",
    trivia: "紋章にケツァール鳥（自由の象徴）が描かれる。この鳥は囚われると死ぬとされる。" },
  { num: 92, code: "GU", emoji: "🇬🇺", name: "グアム", nameEn: "Guam", status: "defacto",
    overview: "西太平洋のアメリカ準州。マリアナ諸島最大の島。米軍基地があり戦略的に重要。",
    colorRules: "Dark Blue 281 C・Red 032 C。領土法が寸法を法定するがPantone未規定。London 2012値。",
    trivia: "楕円形シールにプロア（帆船）、ココヤシ、河口風景が描かれる。赤枠は2インチと法定。" },
  { num: 93, code: "GW", emoji: "🇬🇼", name: "ギニアビサウ", nameEn: "Guinea-Bissau", status: "defacto",
    overview: "西アフリカの小国。1974年にポルトガルから独立。カシューナッツが主要輸出品。",
    colorRules: "Red 032 C・Yellow 109 C・Green 355 C。政府の法定Pantone指定なし。標準近似値を適用。",
    trivia: "黒い五芒星はアフリカの統一を象徴。パン・アフリカニズムの影響を受けたデザイン。" },
  { num: 94, code: "GY", emoji: "🇬🇾", name: "ガイアナ", nameEn: "Guyana", status: "defacto",
    overview: "南米北東部の英語圏国家。カイエトゥール滝（世界最大級の単一落差）で有名。",
    colorRules: "Green・Golden Yellow 109 C・Red 032 C・White・Black。公式Pantone仕様なし。",
    trivia: "「Golden Arrowhead（金の矢じり）」の愛称。三角形が入れ子になった独特のダイナミックな旗。" },
  { num: 95, code: "HK", emoji: "🇭🇰", name: "香港", nameEn: "Hong Kong", status: "dejure",
    overview: "中国の特別行政区。アジアの国際金融センター。1997年の英国返還後も独自の法体系を維持。",
    colorRules: "Red 186 C。区旗及び区章条例で厳格に法定。中国国旗の赤と同一であることが規定。",
    trivia: "白いバウヒニアの花に赤い五線が入った意匠。Blakeana種は香港固有の自然の象徴。" },
  { num: 96, code: "HM", emoji: "🇭🇲", name: "ハード島とマクドナルド諸島", nameEn: "Heard Island", status: "dejure",
    overview: "インド洋南部のオーストラリア外部領。無人の火山島。ビッグ・ベン火山が活動中。",
    colorRules: "Blue 280 C・Red 185 C。オーストラリア国旗と同一。首相内閣省の公式値をそのまま適用。",
    trivia: "無人島のため独自の旗はなくオーストラリア国旗を使用。南極条約の対象外。" },
  { num: 97, code: "HN", emoji: "🇭🇳", name: "ホンジュラス", nameEn: "Honduras", status: "dejure",
    overview: "中米の共和国。カリブ海に面し、コパン遺跡（マヤ文明）とベイ島リゾートで有名。",
    colorRules: "Navy Blue（#0D3B99）。2026年1月にターコイズからネイビーブルーに公式復帰した最新法令。",
    trivia: "1949年法令ではターコイズと明記されていたが70年以上ネイビーで製造されてきた慣行を政府が追認。" },
  { num: 98, code: "HR", emoji: "🇭🇷", name: "クロアチア", nameEn: "Croatia", status: "defacto",
    overview: "アドリア海に面する南東ヨーロッパの国。ドゥブロヴニクの旧市街が世界遺産。",
    colorRules: "Red 186 C・Blue 280 C。国会（Sabor）が建設シートを提供。紋章にLight Blue/Yellowも使用。",
    trivia: "紋章の赤白チェック柄（šahovnica）はクロアチアの歴史的象徴。王冠の5紋章は5つの歴史的地域。" },
  { num: 99, code: "HT", emoji: "🇭🇹", name: "ハイチ", nameEn: "Haiti", status: "defacto",
    overview: "カリブ海のイスパニョーラ島西部の国。1804年に世界初の黒人共和国として独立。",
    colorRules: "Blue 282 C・Red 186 C。憲法に青と赤の記載があるが色コードは規定なし。",
    trivia: "旗の格言「L'Union fait la force（団結は力なり）」。紋章に王ヤシと自由の帽子が描かれる。" },
  { num: 100, code: "HU", emoji: "🇭🇺", name: "ハンガリー", nameEn: "Hungary", status: "dejure",
    overview: "中央ヨーロッパの内陸国。ドナウ川流域。ブダペストの温泉とグヤーシュ料理で有名。",
    colorRules: "Red 186 C・Green 348 C。MSZ 1361:2009でPantone TCXシステムにより法定（De jure）。",
    trivia: "Red TCX名は「Tomato」、Green TCX名は「Fairway」。織物製造用のTCXシステムで定義される珍しい例。" },
  { num: 101, code: "ID", emoji: "🇮🇩", name: "インドネシア", nameEn: "Indonesia", status: "defacto", tags: ["unique"],
    overview: "東南アジアの島嶼国家。約17,000の島と2億7千万人超。約300の民族が共存。",
    colorRules: "Red（CMYK: 0,100,100,0）。赤はRGB 255,0,0の鮮明な赤と規定。「Sang Merah Putih」。",
    trivia: "モナコ国旗とほぼ同一デザインだがインドネシアの方が先。国連も両方を認めている。" },
  { num: 102, code: "IE", emoji: "🇮🇪", name: "アイルランド", nameEn: "Ireland", status: "defacto",
    overview: "北西ヨーロッパの島国。ケルト文化の宝庫。「千の歓迎の島」の異名。IT産業の欧州拠点。",
    colorRules: "Green 347 C・Orange 151 C。政府旗章プロトコルで引用される値。技術的色値の法規定なし。",
    trivia: "緑はカトリック、橙はプロテスタント（オレンジ団）、白は両者の平和と調和。1848年に初使用。" },
  { num: 103, code: "IL", emoji: "🇮🇱", name: "イスラエル", nameEn: "Israel", status: "defacto",
    overview: "中東の地中海東岸国。1948年建国のユダヤ人国家。「スタートアップ・ネイション」の異名。",
    colorRules: "Blue 2728 C。国旗法は「暗い空色（テヘレット）」と記述するが技術定義なし。比率8:11。",
    trivia: "ダビデの星と2本の青帯はユダヤ教の祈禱用肩掛け「タリート」のデザインに基づくとされる。" },
  { num: 104, code: "IM", emoji: "🇮🇲", name: "マン島", nameEn: "Isle of Man", status: "defacto",
    overview: "アイリッシュ海の王室属領。世界最古の議会ティンワルド。TTレースで世界的に有名。",
    colorRules: "Red・Gold 108 C。法定Pantone規定なし。CRW Flags準拠。",
    trivia: "トリスケリオン（三脚巴）は13世紀に由来。三本の武装した脚は「どちらに投げられても立つ」の意。" },
  { num: 105, code: "IN", emoji: "🇮🇳", name: "インド", nameEn: "India", status: "dejure",
    overview: "南アジアの大国。14億人超の世界最大人口。多様な言語・宗教・文化が共存する。",
    colorRules: "India Saffron・India Green 348 C・Navy Blue 2755 C。BIS IS 1でCIE 1931色空間で法定。",
    trivia: "中央のアショーカ・チャクラ（24本の輻）は法の輪。チャクラの色は海軍色でインド海軍旗にも使用。" },
  { num: 106, code: "IO", emoji: "🇮🇴", name: "イギリス領インド洋地域", nameEn: "BIOT", status: "defacto",
    overview: "インド洋中部の英海外領。ディエゴガルシア島に米英共同軍事基地。主権は国際係争中。",
    colorRules: "Blue 281 C。固有のPantone法令なし。紋章にヤシの木・王冠・波型縞を配する。",
    trivia: "2019年ICJ勧告でモーリシャスへの返還が求められている係争地。紋章にヤシと王冠。" },
  { num: 107, code: "IQ", emoji: "🇮🇶", name: "イラク", nameEn: "Iraq", status: "defacto",
    overview: "中東のチグリス・ユーフラテス川流域。メソポタミア文明の発祥地。石油大国。",
    colorRules: "Red 185 C・Green 355 C・Black 6 C。Album des Pavillonsの汎アラブ色の標準近似値。",
    trivia: "白帯に緑のクーフィー体で「アッラーフ・アクバル」と記載。書体は2008年に手書き体から変更。" },
  { num: 108, code: "IR", emoji: "🇮🇷", name: "イラン", nameEn: "Iran", status: "defacto",
    overview: "中東の大国。ペルシャ帝国の後継国家。独自の文化・言語圏を持つイスラム共和国。",
    colorRules: "Green 355 C・Red 186 C。ISIRI 1は構造を規定するがPantone定義を厳密には含まない。",
    trivia: "帯の境界に「アッラーフ・アクバル」が22回繰り返し配置（イスラム革命のバフマン月22日を象徴）。" },
  { num: 109, code: "IS", emoji: "🇮🇸", name: "アイスランド", nameEn: "Iceland", status: "dejure",
    overview: "北大西洋の火山島国。氷河と温泉が共存する「火と氷の国」。世界最古の民主議会を持つ。",
    colorRules: "Blue SCOTDIC 693009・Red 1795 C。1944年法律でDe jure指定。SCOTDIC色標準を採用。",
    trivia: "色の公式名は「Fiery Red」「Snow White」「Light Blue」。記述的色名を持つ珍しい例。" },
  { num: 110, code: "IT", emoji: "🇮🇹", name: "イタリア", nameEn: "Italy", status: "dejure",
    overview: "南ヨーロッパのブーツ型の半島国。古代ローマの遺産、ルネサンスの芸術、食文化の国。",
    colorRules: "Green 17-6153 TCX・Red 18-1662 TCX。2006年官報第174号でPantone TCX織物値が法定。",
    trivia: "基準見本は国務儀典局・県庁・在外公館に保管。緑はFern Green、赤はScarlet Redが正式TCX名。" },
  { num: 111, code: "JE", emoji: "🇯🇪", name: "ジャージー", nameEn: "Jersey", status: "defacto",
    overview: "イギリス海峡の王室属領。独自の議会と法制度。金融サービスとジャージー牛で有名。",
    colorRules: "Red・Gold 108 C。法定Pantone規定なし。白地に赤いサルタイアーと紋章を配する。",
    trivia: "紋章の3頭の豹はノルマンディー公に由来。プランタジネット冠が添えられている。" },
  { num: 112, code: "JM", emoji: "🇯🇲", name: "ジャマイカ", nameEn: "Jamaica", status: "defacto", tags: ["unique"],
    overview: "カリブ海第3の島国。レゲエ・ボブマーリーの故郷。ブルーマウンテンコーヒーの産地。",
    colorRules: "Gold 109 C・Green 355 C・Black C。Jamaica 55等の政府印刷仕様で引用。",
    trivia: "世界で唯一、赤・白・青のいずれも使用しない国旗。金のX字は太陽と困難の克服を象徴。" },
  { num: 113, code: "JO", emoji: "🇯🇴", name: "ヨルダン", nameEn: "Jordan", status: "dejure",
    overview: "中東の立憲君主国。ペトラ遺跡と死海で世界的に有名。安定した国家運営で知られる。",
    colorRules: "Crimson 200 C・Green 349 C・Black C。2007年王室プロトコルで「深紅」が公式（De jure）。",
    trivia: "七芒星はクルアーン冒頭の7節を象徴。汎アラブ色にハーシム王朝の深紅三角を加えた伝統旗。" },
  { num: 114, code: "JP", emoji: "🇯🇵", name: "日本", nameEn: "Japan", status: "dejure",
    overview: "東アジアの島国。7000近い島で構成。世界第3位の経済大国で独自の文化・技術で世界に貢献。",
    colorRules: "Crimson 186 C（紅色/Munsell 5R 4/12）。1999年「国旗及び国歌に関する法律」で法定。",
    trivia: "日章旗の赤は純粋な赤ではなく日本の伝統色「紅」。防衛省はMunsell、ODA文書はDIC 156を公式参照。" },
  { num: 115, code: "KE", emoji: "🇰🇪", name: "ケニア", nameEn: "Kenya", status: "defacto",
    overview: "東アフリカの赤道直下の国。サファリの聖地で野生動物の宝庫。マラソン大国。",
    colorRules: "Red 180 C・Green 347 C・Black・White。憲法がデザインを定めるがPantone色値は規定なし。",
    trivia: "中央のマサイ族の盾と交差した槍は独立と自由を守る意志の象徴。1963年独立時に正式採用。" },
  { num: 116, code: "KG", emoji: "🇰🇬", name: "キルギス", nameEn: "Kyrgyzstan", status: "defacto",
    overview: "中央アジアの山岳国。天山山脈とイシク・クル湖で知られる遊牧文化の国。",
    colorRules: "Red 1788 C・Yellow C。法定Pantone規定なし。既存値は正確と確認されている。",
    trivia: "太陽の40本の光線はマナスに統一された40の部族を象徴。中央のテュンドゥクはユルトの天井構造。" },
  { num: 117, code: "KH", emoji: "🇰🇭", name: "カンボジア", nameEn: "Cambodia", status: "defacto", tags: ["unique"],
    overview: "東南アジアの王国。アンコール・ワット遺跡群で世界的に有名。メコン川が農業・漁業を支える。",
    colorRules: "Blue 286 C・Red（帯幅比1:2:1）・Black 6 C。法定Pantone値なし。標準近似値を使用。",
    trivia: "世界で唯一、建物（アンコール・ワット三塔）を国旗に描いた国。クメール文明の誇りの象徴。" },
  { num: 118, code: "KI", emoji: "🇰🇮", name: "キリバス", nameEn: "Kiribati", status: "dejure",
    overview: "太平洋中部の島嶼国家。33の環礁で世界最大の排他的経済水域。海面上昇の危機に直面。",
    colorRules: "Red 032 C・Gold 109 C・Blue 286 C。国家アイデンティティ法1989年で法定（De jure）。",
    trivia: "軍艦鳥（te eitei）が太陽の上を飛ぶ意匠。17本の光線はギルバート16島＋バナバ島を表す。" },
  { num: 119, code: "KM", emoji: "🇰🇲", name: "コモロ", nameEn: "Comoros", status: "defacto",
    overview: "インド洋西部の島国。4つの主要島。バニラ・イランイラン・丁子の世界的産地。",
    colorRules: "Green 355 C・Yellow 109 C・Red 032 C・Blue 286 C。憲法は色を文言で記述。Pantone仕様なし。",
    trivia: "四色帯は4島を表す。黄=モヘリ、白=マヨット、赤=アンジュアン、青=グランドコモル。" },
  { num: 120, code: "KN", emoji: "🇰🇳", name: "セントクリストファー・ネイビス", nameEn: "Saint Kitts and Nevis", status: "dejure",
    overview: "カリブ海の二島国家。西半球最小の主権国家。かつての「砂糖の島」。観光と金融が主産業。",
    colorRules: "Green 349 C・Red 186 C・Yellow 108 C。外務省公式サイトが公式Pantone仕様を公表（De jure）。",
    trivia: "2つの白い星はセントキッツとネイビスの両島（希望と自由）を象徴。斜め黒帯が旗を分割。" },
  { num: 121, code: "KP", emoji: "🇰🇵", name: "北朝鮮", nameEn: "North Korea", status: "defacto",
    overview: "朝鮮半島北部の社会主義国家。主体思想を国家理念とし閉鎖的な体制で国際的に孤立。",
    colorRules: "Red 1788 C・Blue 2145 C。政府はPantone非公開。Album des Pavillons 2023が最も権威ある参照。",
    trivia: "韓国との「旗戦争」で互いに巨大旗を掲げ合った逸話がある。白い円の赤い五芒星は革命の伝統。" },
  { num: 122, code: "KR", emoji: "🇰🇷", name: "韓国", nameEn: "South Korea", status: "dejure",
    overview: "朝鮮半島南部の先進国。Kポップ・韓国料理・半導体で世界的影響力。ネット普及率世界トップ。",
    colorRules: "Red 186 C・Blue 294 C・Black C。「大韓民国国旗法」でCIE/マンセル座標により法定。",
    trivia: "太極旗の中央は陰陽（太極）、四隅の四卦は天地水火。東洋哲学を国旗に取り入れた世界的に珍しい例。" },
  { num: 123, code: "KW", emoji: "🇰🇼", name: "クウェート", nameEn: "Kuwait", status: "defacto",
    overview: "ペルシャ湾北西岸の石油立国。世界有数の石油埋蔵量を持つ裕福な首長国。",
    colorRules: "Green 340 C・Red 186 C・Black C。法定Pantone規定なし。汎アラブ色の標準近似値を使用。",
    trivia: "汎アラブ色は7世紀のアラブ詩人サフィー・アッディーンの詩にも登場する歴史的な配色。" },
  { num: 124, code: "KY", emoji: "🇰🇾", name: "ケイマン諸島", nameEn: "Cayman Islands", status: "defacto",
    overview: "カリブ海のイギリス海外領土。3つの島からなるオフショア金融センター。ウミガメで有名。",
    colorRules: "Blue 281 C・Red 032 C。英ブルー・エンサイン。London 2012旗章マニュアルが参照値を提供。",
    trivia: "紋章に3星（3島）、ウミガメ（海洋遺産）、パイナップル（カリブのもてなし精神）が描かれる。" },
  { num: 125, code: "KZ", emoji: "🇰🇿", name: "カザフスタン", nameEn: "Kazakhstan", status: "dejure",
    overview: "中央アジア最大の国。石油と鉱物の資源大国。バイコヌール宇宙基地がある。",
    colorRules: "Sky Blue 3125 C・Gold 102 C。国家規格ST-RK 988-2007で公式定義（De jure）。",
    trivia: "太陽は繁栄、32本の光線は進歩、草原の鷲は独立。金色の民族装飾帯はカザフの伝統工芸に由来。" },
  { num: 126, code: "LA", emoji: "🇱🇦", name: "ラオス", nameEn: "Laos", status: "defacto",
    overview: "東南アジアの内陸国。メコン川沿いの仏教国。「百万頭の象の国」の異名を持つ。",
    colorRules: "Red 186 C・Blue 280 C。1975年採用。法定Pantone指定なし。赤帯の倍幅の青帯を中央に配する。",
    trivia: "白い円盤はメコン川に映る満月。共産諸国の旗で鎌・槌・星を使わないデザインは珍しい。" },
  { num: 127, code: "LB", emoji: "🇱🇧", name: "レバノン", nameEn: "Lebanon", status: "defacto",
    overview: "地中海東岸の小国。フェニキア文明の発祥地。中東の金融・文化中心地。",
    colorRules: "Red 1788 C・Green 355 C。憲法でデザイン定義。1990年明確化で杉全体が緑でなければならない。",
    trivia: "1990年の法的明確化で「茶色の幹を持つ杉」は違憲と判断された。レバノン杉は聖書にも登場。" },
  { num: 128, code: "LC", emoji: "🇱🇨", name: "セントルシア", nameEn: "Saint Lucia", status: "defacto",
    overview: "カリブ海東部の小島国。双子のピトン山（世界遺産）が象徴。バナナ・カカオ生産が主要産業。",
    colorRules: "Cerulean Blue・Gold・Black C。公式色名を使用。Process Cyan 100%とLight Chrome Yellowを参照。",
    trivia: "Dunstan St. Omerがデザイン。金と黒の三角形が双子のピトン山（火山）を表現する美しい意匠。" },
  { num: 129, code: "LI", emoji: "🇱🇮", name: "リヒテンシュタイン", nameEn: "Liechtenstein", status: "defacto",
    overview: "アルプスの小国。世界で最も裕福な国の一つ。金融と精密機器産業で知られる。",
    colorRules: "Blue 280 C・Red 186 C・Gold 116 C。1982年国家シンボル法でデザイン規定。Album参照。",
    trivia: "1936年ベルリン五輪でハイチと旗が同一と判明。翌年に金の公爵冠を追加したエピソードが有名。" },
  { num: 130, code: "LK", emoji: "🇱🇰", name: "スリランカ", nameEn: "Sri Lanka", status: "dejure",
    overview: "インド洋の島国。セイロン島に位置し、紅茶、宝石、仏教遺跡で有名。多民族国家。",
    colorRules: "Maroon 152 C・Gold 124 C・Green 3302 C。SLS 1:2020で公式CMYK/HEX値を法定。",
    trivia: "ライオンはシンハラ人の勇気、菩提樹の葉は仏教の四徳。緑帯はムーア人、サフラン帯はタミル人。" },
  { num: 131, code: "LR", emoji: "🇱🇷", name: "リベリア", nameEn: "Liberia", status: "defacto",
    overview: "西アフリカの共和国。解放奴隷が1847年に建国。アフリカ最古の共和国。",
    colorRules: "Red 186 C・Blue 281 C・White。旗章法がデザインを定めるがPantone値は規定なし。",
    trivia: "米国旗と似たデザインだが星は1つ（孤星）。11本の縞は独立宣言への署名者11人を象徴。" },
  { num: 132, code: "LS", emoji: "🇱🇸", name: "レソト", nameEn: "Lesotho", status: "dejure",
    overview: "南アフリカに完全に囲まれた内陸国。全土が標高1400m以上の「天空の王国」。",
    colorRules: "Reflex Blue C・Green 347 C・Black 6 C。2006年国旗法で指定。De jure。",
    trivia: "2006年独立40周年に新旗を採用。黒いモコロトロ（バソト族の円錐形帽子）が白帯中央に配される。" },
  { num: 133, code: "LT", emoji: "🇱🇹", name: "リトアニア", nameEn: "Lithuania", status: "dejure",
    overview: "バルト三国最南の国。中世のリトアニア大公国は欧州最大だった。バスケットボール大国。",
    colorRules: "Yellow 1235 C・Green 349 C・Red 180 C。国旗法でPantone TPシステムにより法定。",
    trivia: "黄は太陽と豊穣、緑は田園風景、赤は国のために流された血。パンスラヴ色ではなく独自の配色。" },
  { num: 134, code: "LU", emoji: "🇱🇺", name: "ルクセンブルク", nameEn: "Luxembourg", status: "dejure",
    overview: "西ヨーロッパの小国。世界最高水準の一人当たりGDP。EU多くの機関が所在。",
    colorRules: "Red 032 C・Light Blue 299 C。1993年大公令でPantoneを法定。オランダ旗との区別が法的要件。",
    trivia: "オランダ国旗とほぼ同じだが青が「淡青」。この色の違いが法的に義務づけられている。" },
  { num: 135, code: "LV", emoji: "🇱🇻", name: "ラトビア", nameEn: "Latvia", status: "dejure",
    overview: "バルト三国中央の国。リガ旧市街のアール・ヌーヴォー建築が有名。合唱祭はユネスコ遺産。",
    colorRules: "Carmine Red 201 C（2018年改正で確定）。織物用は19-1629 TPX/TC。帯比率2:1:2。",
    trivia: "世界最古の旗のひとつ（1280年の記録）。独特の「カーマインレッド」は中世の戦いの伝説に由来。" },
  { num: 136, code: "LY", emoji: "🇱🇾", name: "リビア", nameEn: "Libya", status: "defacto",
    overview: "北アフリカのアラブ国家。地中海に面し、サハラ砂漠が国土の大半。石油が主な資源。",
    colorRules: "Red 485 C・Green 348 C・Black C。政府発行のPantone仕様なし。標準近似値を使用。",
    trivia: "2011年に復活した1951年憲法の旗。カダフィ時代（1977-2011）は世界唯一の単色旗（全面緑）だった。" },
  { num: 137, code: "MA", emoji: "🇲🇦", name: "モロッコ", nameEn: "Morocco", status: "defacto",
    overview: "北アフリカの王国。マラケシュのメディナとサハラ砂漠ツアーで観光大国。",
    colorRules: "Red 7620 C（暗く落ち着いた赤）・Green 3425 C（棕櫚緑）。ダヒールで定義。特殊な暗色系。",
    trivia: "赤地に緑の五芒星（ソロモンの印章）。幾何学仕様は厳密で半径=旗長の1/6、枝幅=星長の1/20。" },
  { num: 138, code: "MC", emoji: "🇲🇨", name: "モナコ", nameEn: "Monaco", status: "defacto", tags: ["unique"],
    overview: "フランスに囲まれた世界第2位の小国。F1グランプリとカジノの国。モンテカルロが代名詞。",
    colorRules: "Red 186 C。1881年公主令でデザイン規定。色の具体的指定なし。公式比率は4:5。",
    trivia: "インドネシア国旗とほぼ同一だが比率が異なる。グリマルディ家の紋章（1339年以来）に由来。" },
  { num: 139, code: "MD", emoji: "🇲🇩", name: "モルドバ", nameEn: "Moldova", status: "dejure",
    overview: "東欧の内陸国。ルーマニアとウクライナに挟まれた旧ソ連構成国。ワイン生産地として有名。",
    colorRules: "Blue・Yellow・Red。2010年法で法定。色名は「ベルリン紺青・クロームイエロー・朱赤」。",
    trivia: "ルーマニア国旗と同じ三色旗に国章を追加。紋章はオーロクス（牛）を含み中世の国章に由来。" },
  { num: 140, code: "ME", emoji: "🇲🇪", name: "モンテネグロ", nameEn: "Montenegro", status: "defacto",
    overview: "バルカン半島南西部のアドリア海沿岸国。2006年にセルビアから独立した欧州最新の独立国。",
    colorRules: "Red 186 C・Gold 117 C。法定Pantone値なし。赤地に金の縁取り（旗高の1/20）を配する。",
    trivia: "国章の双頭の鷲は笏と十字架球を持つ。赤と金の構成はハプスブルクとビザンチンの融合を表す。" },
  { num: 141, code: "MF", emoji: "🇲🇫", name: "サン・マルタン", nameEn: "Saint Martin (FR)", status: "dejure",
    overview: "カリブ海のフランス海外準県。セント・マーチン島の北部。南部はオランダ領。",
    colorRules: "Blue 072 C・Red 485 C。NF X 08002（AFNOR規格）に基づくフランス三色旗の色仕様。",
    trivia: "一つの島が仏蘭2カ国に分割されている世界的にも珍しい例。両側の住民は自由に行き来可能。" },
  { num: 142, code: "MG", emoji: "🇲🇬", name: "マダガスカル", nameEn: "Madagascar", status: "defacto",
    overview: "世界第4位の大きさの島国。固有種が90%以上というバイオホットスポット。バニラ生産世界一。",
    colorRules: "Warm Red C・Green 348 C。Album des Pavillonsが引用する値として確認。White帯がホイスト側。",
    trivia: "白はメリナ王国の王権の伝統色。赤もメリナの統治、緑は平民と沿岸民の結びつきを表す。" },
  { num: 143, code: "MH", emoji: "🇲🇭", name: "マーシャル諸島", nameEn: "Marshall Islands", status: "defacto",
    overview: "太平洋中部の環礁国家。ビキニ環礁（核実験場跡）は世界遺産。米国との自由連合。",
    colorRules: "Blue 287 C・Orange 152 C。旗章法1979年がデザイン規定。公式色名は「Orange」。",
    trivia: "24芒星の24の点は24の自治体を表す。白と橙の2帯が下ホイストから上フライへ伸びる独特デザイン。" },
  { num: 144, code: "MK", emoji: "🇲🇰", name: "北マケドニア", nameEn: "North Macedonia", status: "defacto",
    overview: "バルカン半島中部の内陸国。1991年ユーゴスラビアから独立。2019年にギリシャとの係争で改名。",
    colorRules: "Red 485 C・Yellow 108 C。1995年国旗法採用。Album des Pavillonsの標準値に基づく。",
    trivia: "旧ヴェルギナ太陽はギリシャの抗議でこの放射線デザインに変更。太陽光線が旗の端まで伸びる独特意匠。" },
  { num: 145, code: "ML", emoji: "🇲🇱", name: "マリ", nameEn: "Mali", status: "defacto",
    overview: "西アフリカの内陸国。サハラ砂漠南縁。トンブクトゥは中世の学問都市。金の産出国。",
    colorRules: "Green 355 C・Gold 109 C・Red 186 C。法定Pantone値なし。公式呼称「Gold」を使用。",
    trivia: "1959年のマリ連邦旗からカナガ像（ドゴン族の象徴）を除去して1961年制定。仏三色旗がモデル。" },
  { num: 146, code: "MM", emoji: "🇲🇲", name: "ミャンマー", nameEn: "Myanmar", status: "defacto",
    overview: "東南アジア西部の国。豊富な天然資源と仏教文化。バガン遺跡群は世界遺産。",
    colorRules: "Yellow 116 C・Green 361 C・Red 1788 C。ミャンマー大使館（ベルリン）が公式Pantone PC値を提供。",
    trivia: "2010年新憲法に伴い国旗を変更。白い五芒星が3色帯全てに重なる大胆なデザイン。変更は深夜に実施。" },
  { num: 147, code: "MN", emoji: "🇲🇳", name: "モンゴル", nameEn: "Mongolia", status: "dejure",
    overview: "東アジアの内陸国。チンギス・ハーンの帝国の後継。大草原の遊牧文化と極端な気候。",
    colorRules: "Red 032 C・Blue 660 C・Yellow 116 C。2011年公式色標準化でDe jure指定。以前の値から全面更新。",
    trivia: "ソヨンボ紋章は火・太陽・月・矢・魚・柱・陰陽の複合意匠。モンゴル文字から派生した国章。" },
  { num: 148, code: "MO", emoji: "🇲🇴", name: "マカオ", nameEn: "Macao", status: "dejure",
    overview: "中国の特別行政区。1999年ポルトガルから返還。カジノ収入世界一の「東洋のラスベガス」。",
    colorRules: "Green 3295 C・Yellow 109 C。GB 17654-1999（中国国家標準）で法定。",
    trivia: "白い蓮花の三枚花弁はマカオ半島・タイパ島・コロアネ島の3地域を象徴。五つの金星は中国との結びつき。" },
  { num: 149, code: "MP", emoji: "🇲🇵", name: "北マリアナ諸島", nameEn: "Northern Mariana Islands", status: "defacto",
    overview: "太平洋西部のアメリカ自治連邦領。サイパンが主要島。第二次世界大戦の激戦地。",
    colorRules: "Blue 286 C・Grey 421 C。CNMI法令にPantone指定なし。CRW Flags準拠。",
    trivia: "ラッテ・ストーン（古代チャモロ建築の柱）と白い星。ムワール（花輪）はカロリン族の文化を象徴。" },
  { num: 150, code: "MQ", emoji: "🇲🇶", name: "マルティニーク", nameEn: "Martinique", status: "dejure",
    overview: "カリブ海のフランス海外県。プレー火山で知られる火山島。「AOCマルティニーク」ラム酒を生産。",
    colorRules: "Blue 072 C・Red 485 C。NF X 08002に基づくフランス三色旗。De jure確認済み。",
    trivia: "非公式の緑地蛇旗が有名だが法的地位はない。フランスのEU最遠隔地域の一つ。" },
  { num: 151, code: "MR", emoji: "🇲🇷", name: "モーリタニア", nameEn: "Mauritania", status: "defacto",
    overview: "西アフリカ。国土のほぼ全域がサハラ砂漠。鉄鉱石と漁業が主要産業。",
    colorRules: "Green 354 C・Gold・Red 186 C。2017年国民投票で赤帯を追加。2020年チャーターで色を更新。",
    trivia: "2017年に初めて赤帯を追加（独立闘争の血を象徴）。三日月・星はイスラム、金は砂漠の砂を表す。" },
  { num: 152, code: "MS", emoji: "🇲🇸", name: "モントセラト", nameEn: "Montserrat", status: "defacto",
    overview: "カリブ海の英海外領土。1995年の火山噴火で首都が壊滅。人口は約5000人に減少。",
    colorRules: "Blue 280 C・Red 186 C。英国ブルー・エンサイン。MoD BR20に基づく。",
    trivia: "紋章の「エリン」はアイルランドの女性擬人化。開拓者がアイルランド系カトリック移民だった歴史を示す。" },
  { num: 153, code: "MT", emoji: "🇲🇹", name: "マルタ", nameEn: "Malta", status: "dejure", tags: ["unique"],
    overview: "地中海中央の島国。マルタ騎士団の歴史と巨石神殿群で知られる。EUの最小加盟国。",
    colorRules: "Red 186 C（50% rubine red / 50% warm red）。首相府2008年仕様書でDe jure指定。",
    trivia: "ジョージ・クロスが国旗にある世界唯一の国。1942年に英国王から授与された軍事勲章が国旗に配される。" },
  { num: 154, code: "MU", emoji: "🇲🇺", name: "モーリシャス", nameEn: "Mauritius", status: "dejure",
    overview: "インド洋の島国。「インド洋の貴婦人」の異名。多民族が調和する観光立国。",
    colorRules: "Red 1788 C・Blue 2756 C・Yellow 012 C・Green 7482 C。2015年法律でDe jure。全4色を修正。",
    trivia: "「Les Quatre Bandes」の愛称。赤は独立闘争の血、青はインド洋、黄は独立の光、緑は農業。" },
  { num: 155, code: "MV", emoji: "🇲🇻", name: "モルディブ", nameEn: "Maldives", status: "defacto",
    overview: "インド洋の環礁国家。約1200の島。世界最低地の国。高級リゾートと海面上昇の脅威。",
    colorRules: "Red 186 C・Green 348 C。Album des Pavillonsで確認。赤い枠に緑の長方形と白い三日月。",
    trivia: "赤い枠（幅=旗幅の1/4）は国民の血と勇気、緑はイスラム、白い三日月はイスラム信仰を象徴。" },
  { num: 156, code: "MW", emoji: "🇲🇼", name: "マラウイ", nameEn: "Malawi", status: "defacto",
    overview: "東南アフリカの内陸国。マラウイ湖が国土の約1/5。「アフリカの温かい心」の異名。",
    colorRules: "Red 186 C・Green 356 C・Black C。2012年に1964年のデザインに復活。標準近似値を使用。",
    trivia: "赤い昇る太陽の31本の光線はアフリカ31番目の独立国。2010年の太陽変更は不評で撤回された。" },
  { num: 157, code: "MX", emoji: "🇲🇽", name: "メキシコ", nameEn: "Mexico", status: "dejure",
    overview: "北米南部の大国。アステカ・マヤ文明の遺産と多彩な食文化で世界的に有名。",
    colorRules: "Green 3425 C・Red 186 C。内務省が推奨するPantone値でDe jure指定。独自比率4:7。",
    trivia: "国章はアステカの伝説「サボテンの上で蛇を食む鷲」。この場所にメキシコシティを建設。" },
  { num: 158, code: "MY", emoji: "🇲🇾", name: "マレーシア", nameEn: "Malaysia", status: "defacto",
    overview: "東南アジアの連邦国家。多民族・多宗教国家。半導体とパームオイルが主要産業。",
    colorRules: "Red 485 C・Blue 286 C・Yellow 109 C。公式Pantone仕様が非公開のためソース間に矛盾あり。",
    trivia: "「Jalur Gemilang（栄光の縞）」。14本の赤白帯と14芒星は13州と連邦。三日月はイスラム教の象徴。" },
  { num: 159, code: "MZ", emoji: "🇲🇿", name: "モザンビーク", nameEn: "Mozambique", status: "defacto", tags: ["unique"],
    overview: "南東アフリカのインド洋沿岸国。1975年ポルトガルから独立。天然ガス開発で成長期待。",
    colorRules: "Green 355 C・Yellow 109 C・Red 185 C・Black C。London 2012旗マニュアル値を採用。",
    trivia: "世界で唯一、近代火器（AK-47銃剣付き）が国旗に描かれている国。独立闘争と防衛の決意を象徴。" },
  { num: 160, code: "NA", emoji: "🇳🇦", name: "ナミビア", nameEn: "Namibia", status: "defacto",
    overview: "南西アフリカの国。ナミブ砂漠とエトーシャ国立公園が有名。人口密度は世界最低級。",
    colorRules: "Blue Reflex Blue C・Red 485 C・Yellow 123 C・Green 347 C。Album des Pavillonsで確認。",
    trivia: "太陽の12本の光線は12の民族を象徴。対角線の赤い帯は独立闘争を表す力強いデザイン。" },
  { num: 161, code: "NC", emoji: "🇳🇨", name: "ニューカレドニア", nameEn: "New Caledonia", status: "dejure",
    overview: "南太平洋のフランス海外特別共同体。ニッケル埋蔵量は世界有数。独立問題が続く。",
    colorRules: "Blue 072 C・Red 485 C。公式旗はフランス三色旗。カナク旗は並掲されるが法的地位なし。",
    trivia: "カナク旗は2010年議会決議で三色旗と並掲を承認。フレーシュ・ファイティエール（屋根飾り矢）が象徴。" },
  { num: 162, code: "NE", emoji: "🇳🇪", name: "ニジェール", nameEn: "Niger", status: "defacto",
    overview: "西アフリカの内陸国。サハラ砂漠が国土の約2/3。ウランの主要産出国。",
    colorRules: "Orange 166 C・Green 361 C。比率6:7のほぼ正方形で珍しい。政府Pantone仕様なし。",
    trivia: "白帯中央のオレンジ円盤は太陽。オレンジはサハラ砂漠、白は純潔、緑は肥沃な南部を表す。" },
  { num: 163, code: "NF", emoji: "🇳🇫", name: "ノーフォーク島", nameEn: "Norfolk Island", status: "dejure",
    overview: "南太平洋のオーストラリア外部領。バウンティ号反乱者の子孫が住む。ノーフォーク松が象徴。",
    colorRules: "Green 356 C。1979年法で法定されたDe jure唯一の立法規定色。三色縦帯（緑白緑、比率7:9:7）。",
    trivia: "中央の緑のノーフォーク島松（Araucaria heterophylla）は島のシンボル。世界で栽培される装飾樹木。" },
  { num: 164, code: "NG", emoji: "🇳🇬", name: "ナイジェリア", nameEn: "Nigeria", status: "defacto",
    overview: "アフリカ最大の人口と経済規模を持つ西アフリカの連邦共和国。石油とノリウッドが有名。",
    colorRules: "Green 355 C。政府文書にPantone値なし。色は「エメラルドグリーン」と記述されている。",
    trivia: "1960年独立時に学生のデザインコンペで選ばれたシンプルな旗。当初の赤い太陽は削除された。" },
  { num: 165, code: "NI", emoji: "🇳🇮", name: "ニカラグア", nameEn: "Nicaragua", status: "defacto", tags: ["unique"],
    overview: "中米最大の面積の国。ニカラグア湖は中米最大の淡水湖。火山列とグラナダが観光資源。",
    colorRules: "Blue 280 C・Green 376 C。1971年法令で現行デザインを再確認。国章の緑は明るい黄緑色。",
    trivia: "ドミニカ国と共に国旗に紫色（虹の中）を使用する稀少な例。国章に5火山・大洋・虹を配する。" },
  { num: 166, code: "NL", emoji: "🇳🇱", name: "オランダ", nameEn: "Netherlands", status: "dejure",
    overview: "北西ヨーロッパの低地国。国土の約1/4が海面下。チューリップ・風車・チーズで有名。",
    colorRules: "Red 186 C・Blue 286 C（CIE近似）。NEN 3055でCIE 1931色空間座標による法定。De jure。",
    trivia: "世界初の三色旗の元祖。オレンジが赤に変わった経緯は海上での視認性が理由とされる16世紀の伝統。" },
  { num: 167, code: "NO", emoji: "🇳🇴", name: "ノルウェー", nameEn: "Norway", status: "defacto",
    overview: "北欧スカンジナビアの王国。フィヨルドと北極圏の大自然が有名。石油基金で世界有数の裕福さ。",
    colorRules: "Red 200 C・Blue 281 C。法律は「深紅」「暗青」とのみ定義。Nordic Council等の事実上の標準。",
    trivia: "旗の中に6カ国の国旗が隠されているとSNSで話題に（仏・蘭・タイ・インドネシア・ポーランド・フィンランド）。" },
  { num: 168, code: "NP", emoji: "🇳🇵", name: "ネパール", nameEn: "Nepal", status: "dejure", tags: ["unique"],
    overview: "ヒマラヤ山脈の国。世界最高峰エベレストを擁する。2008年に共和国に移行。",
    colorRules: "Crimson Red 199 C・Blue 661 C。2015年憲法で精密な幾何学作図法を提供（De jure）。",
    trivia: "世界唯一の非長方形国旗（二重三角ペナント）。ヒマラヤと2つの主要宗教を象徴する特異な形状。" },
  { num: 169, code: "NR", emoji: "🇳🇷", name: "ナウル", nameEn: "Nauru", status: "defacto",
    overview: "南太平洋の世界第3位の小国。リン鉱石枯渇後は経済危機に直面。",
    colorRules: "Blue 280 C・Yellow 123 C。Album des Pavillonsの標準近似値。黄帯高さは旗の1/12。",
    trivia: "黄色い帯は赤道、白い12芒星は12部族。星が帯の下方に配置されるのはナウルが赤道1°南のため。" },
  { num: 170, code: "NU", emoji: "🇳🇺", name: "ニウエ", nameEn: "Niue", status: "defacto",
    overview: "南太平洋のNZ自由連合国。世界最大の隆起珊瑚島。人口は約2000人。",
    colorRules: "Yellow C・Blue 280 C・Red 186 C。1975年Niue Flag Actで採用。標準近似値を使用。",
    trivia: "金黄色地にユニオンジャック。英連邦では珍しい黄色地の旗。南十字星とNZ結びつきの大星を配する。" },
  { num: 171, code: "NZ", emoji: "🇳🇿", name: "ニュージーランド", nameEn: "New Zealand", status: "dejure",
    overview: "南太平洋の島国。マオリ文化と圧倒的な自然景観。ラグビーのオールブラックスで有名。",
    colorRules: "Red 186 C・Blue 280 C。NZ文化遺産省が指定。1981年法で法的に保護のDe jure。",
    trivia: "赤い四芒南十字星がオーストラリアの白い五芒星との違い。2016年のレファレンダムで現行旗を維持。" },
  { num: 172, code: "OM", emoji: "🇴🇲", name: "オマーン", nameEn: "Oman", status: "defacto",
    overview: "アラビア半島南東端の王国。ペルシャ湾とアラビア海に面する古い海洋交易国家。",
    colorRules: "Red 186 C・Green 347 C。Royal Decree 53/2004で旗を規制。比率は4:7。",
    trivia: "国章のハンジャル（短剣）とサイフ（刀）はオマーンの防衛精神の象徴。白は平和と繁栄。" },
  { num: 173, code: "PA", emoji: "🇵🇦", name: "パナマ", nameEn: "Panama", status: "dejure",
    overview: "中米最南端の国。パナマ運河で世界の貿易を結ぶ。国際金融センター。",
    colorRules: "Blue 295 C・Red 187 C。2017年行政令337号で色を標準化（De jure）。旧値から修正。",
    trivia: "四分割旗に2つの星（青＝保守党、赤＝自由党）。白は両党の平和的共存。独立指導者の妻がデザイン。" },
  { num: 174, code: "PE", emoji: "🇵🇪", name: "ペルー", nameEn: "Peru", status: "defacto",
    overview: "南米西部の国。インカ帝国の遺産マチュピチュとナスカの地上絵で世界的に有名。",
    colorRules: "Red 186 C。憲法で赤白赤を定めるがPantone値は規定なし。最も広く引用される近似値。",
    trivia: "市民旗と国章付き国旗の2バージョン。伝説ではサン・マルティン将軍がフラミンゴを見て配色を決めた。" },
  { num: 175, code: "PF", emoji: "🇵🇫", name: "フランス領ポリネシア", nameEn: "French Polynesia", status: "defacto",
    overview: "南太平洋のフランス海外共同体。タヒチが中心。黒真珠、タトゥー文化、バニラで有名。",
    colorRules: "Red 185 C・Blue 286 C・Gold 116 C。1984年採用。Pantone法令なし。標準近似値を使用。",
    trivia: "領土紋章にポリネシアのピローグ（カヌー）と5人の人物。5人は5つの諸島群を表す。" },
  { num: 176, code: "PG", emoji: "🇵🇬", name: "パプアニューギニア", nameEn: "Papua New Guinea", status: "defacto",
    overview: "南太平洋のメラネシア島嶼国。世界で最も言語多様（800以上）な国。生態系が豊か。",
    colorRules: "Red 186 C・Yellow 116 C・Black C。法定Pantone値なし。対角分割の赤と黒が基本。",
    trivia: "金色の極楽鳥（Kumul）は国の誕生と自由を象徴。南十字星5星は南半球の位置を示す。15歳がデザイン。" },
  { num: 177, code: "PH", emoji: "🇵🇭", name: "フィリピン", nameEn: "Philippines", status: "dejure", tags: ["unique"],
    overview: "東南アジアの約7641の島で構成。スペイン・アメリカの統治を経て1946年独立。英語圏のアジア大国。",
    colorRules: "Blue 286 C・Red 193 C・Golden Yellow 122 C。RA 8491（旗章法）でDe jure。Cable番号で法定。",
    trivia: "平和時は青が上、戦争時は赤が上。世界唯一、旗の向きで国の状態を示す公式な仕組みを持つ。" },
  { num: 178, code: "PK", emoji: "🇵🇰", name: "パキスタン", nameEn: "Pakistan", status: "defacto",
    overview: "南アジアのイスラム共和国。世界第5位の人口。K2（世界第2位の高峰）を擁する。",
    colorRules: "Green 343 C。法的Pantone規定なし。「Parcham-e-Sitāra-o-Hilāl」（星と三日月の旗）と呼ぶ。",
    trivia: "白い縦帯（旗の1/4）は少数派の非ムスリム国民を象徴。三日月は進歩、五芒星は光と知識。" },
  { num: 179, code: "PL", emoji: "🇵🇱", name: "ポーランド", nameEn: "Poland", status: "dejure",
    overview: "中央ヨーロッパの国。1989年の民主化運動でソ連圏からの脱却を先導。ショパンの祖国。",
    colorRules: "Red 1795 C（CIE近似）。1980年法でCIE 1931 xyY座標により法定。色差許容ΔE≤8.0。",
    trivia: "インドネシアやモナコの旗を上下反転させたような配色。白は純潔、赤は闘争の血の象徴。" },
  { num: 180, code: "PM", emoji: "🇵🇲", name: "サンピエール島・ミクロン島", nameEn: "Saint Pierre", status: "dejure",
    overview: "カナダ東岸沖のフランス海外準県。北米唯一のフランス領。漁業と観光が主要産業。",
    colorRules: "Blue 072 C・Red 485 C。NF X 08002に基づくフランス三色旗。地方旗に法的地位なし。",
    trivia: "非公式旗にGrande Hermine号と3パネル（バスク・ブルターニュ・ノルマンディー）で移民の歴史を表す。" },
  { num: 181, code: "PN", emoji: "🇵🇳", name: "ピトケアン諸島", nameEn: "Pitcairn Islands", status: "defacto",
    overview: "南太平洋の英海外領土。HMS Bounty反乱者の子孫が住む。人口約50人で世界最少の自治領。",
    colorRules: "Blue 280 C・Red 186 C・Green 364 C・Yellow 107 C。1984年採用。英ブルー・エンサイン。",
    trivia: "紋章にBountyの聖書と錨。1790年の反乱者が無人島で聖書を頼りに暮した歴史の象徴。" },
  { num: 182, code: "PR", emoji: "🇵🇷", name: "プエルトリコ", nameEn: "Puerto Rico", status: "defacto",
    overview: "カリブ海のアメリカ自治連邦領。サルサ音楽発祥の地で、州昇格議論が続く。",
    colorRules: "Blue 281 C（ダーク）・Red 032 C。1952年にダークブルーで公式化。ライト版とは歴史的議論あり。",
    trivia: "キューバ国旗と配色が反転した関係。両国の独立運動家がニューヨークで連帯した歴史から生まれた。" },
  { num: 183, code: "PS", emoji: "🇵🇸", name: "パレスチナ", nameEn: "Palestine", status: "defacto",
    overview: "中東のヨルダン川西岸地区とガザ地区。1988年にパレスチナ国を宣言。国連オブザーバー国家。",
    colorRules: "Red 032 C・Green 355 C・Black C。PLO 1964年採用。公式Pantone標準なし。汎アラブ色。",
    trivia: "1916年のアラブ反乱旗に由来する汎アラブ色。赤い三角の高さは旗長の1/3と定められた伝統的意匠。" },
  { num: 184, code: "PT", emoji: "🇵🇹", name: "ポルトガル", nameEn: "Portugal", status: "defacto",
    overview: "イベリア半島西端の国。大航海時代の海洋帝国。ファドとポートワインで有名。",
    colorRules: "Green 349 C・Red 485 C。1911年法令で「暗緑」「スカーレット」と定性的に定義。Pantone未規定。",
    trivia: "縦分割が左2/5（緑）右3/5（赤）と非対称。天球儀は大航海時代の象徴。5小盾は初代の5戦勝利。" },
  { num: 185, code: "PW", emoji: "🇵🇼", name: "パラオ", nameEn: "Palau", status: "defacto",
    overview: "西太平洋のミクロネシア島嶼国。約340の島。ダイビングの聖地。1994年独立。",
    colorRules: "Process Blue C・Yellow 109 C。London 2012値を採用。比率5:8。",
    trivia: "水色の地に金色の満月。月は日本の太陽と対をなすとの説も。ホイスト寄りオフセンターが正式配置。" },
  { num: 186, code: "PY", emoji: "🇵🇾", name: "パラグアイ", nameEn: "Paraguay", status: "dejure", tags: ["unique"],
    overview: "南米中央の内陸国。パラナ川が流れイタイプダム（世界最大級の水力発電）がある。",
    colorRules: "Red 485 C・Yellow C・Green 355 C等。Decreto(2013)は紋章色のみ規定。帯色は「原色」とのみ。",
    trivia: "世界唯一の表裏異デザイン国旗。表は国章（星・椰子・オリーブ）、裏は国庫章（獅子・フリジア帽）。" },
  { num: 187, code: "QA", emoji: "🇶🇦", name: "カタール", nameEn: "Qatar", status: "dejure", tags: ["unique"],
    overview: "ペルシャ湾の半島国家。天然ガスと石油で世界最高水準のGDP。2022年W杯開催。",
    colorRules: "Maroon 1955 C（Qatar Maroon）。2012年旗法で法定（De jure）。222 Cは旧値。",
    trivia: "比率11:28は世界で最も横長い国旗。9つの鋸歯は1916年の「第9の和解首長国」を意味する。" },
  { num: 188, code: "RE", emoji: "🇷🇪", name: "レユニオン", nameEn: "Réunion", status: "dejure",
    overview: "インド洋西部のフランス海外県。活火山ピトン・ドゥ・ラ・フルネーズがある。",
    colorRules: "Blue 072 C・Red 485 C。NF X 08002に基づくフランス三色旗。De jure確認済み。",
    trivia: "バニラ、砂糖、ラム酒の名産地。フランスの完全な一部でEU加盟領域。クレオール社会が発達。" },
  { num: 189, code: "RO", emoji: "🇷🇴", name: "ルーマニア", nameEn: "Romania", status: "dejure",
    overview: "東ヨーロッパのカルパチア山脈に囲まれた国。ドラキュラ伝説のトランシルバニアが有名。",
    colorRules: "Blue 280 C・Yellow 116 C・Red 186 C。法律75/1994号が2023年改正でPantone/RGB法定化。",
    trivia: "チャド国旗とほぼ同一（青の濃さが僅差）。歴史的色名はコバルト・クロームイエロー・バーミリオン。" },
  { num: 190, code: "RS", emoji: "🇷🇸", name: "セルビア", nameEn: "Serbia", status: "defacto",
    overview: "バルカン半島中西部の内陸国。旧ユーゴスラビアの中心国。テニスのジョコビッチで有名。",
    colorRules: "Red 193 C・Blue 287 C。法は文言で色定義のみ。国旗版は紋章付き。",
    trivia: "紋章の双頭鷲と4つのキリル文字Сは「セルビア人の団結がセルビアを救う」の頭文字。" },
  { num: 191, code: "RU", emoji: "🇷🇺", name: "ロシア", nameEn: "Russia", status: "defacto",
    overview: "世界最大の面積の国。豊富な天然資源と核兵器を保有する連邦国家。",
    colorRules: "Blue 286 C・Red 485 C。連邦憲法法で白青赤を定めるが正確な色調は規定なし。GOST不在。",
    trivia: "ピョートル大帝がオランダ旗にインスピレーションを受け制定。多くのスラヴ三色旗の原型。" },
  { num: 192, code: "RW", emoji: "🇷🇼", name: "ルワンダ", nameEn: "Rwanda", status: "dejure",
    overview: "アフリカ大湖地域の内陸国。1994年のジェノサイドを乗り越え急速な発展を遂げる。",
    colorRules: "Blue 3005 C・Gold 130 C・Yellow 109 C・Green 3415 C。法34/2008号がデザイン定義。",
    trivia: "2001年にジェノサイドの記憶を払拭するため旗を全面刷新。金色太陽は統一と啓蒙を象徴。" },
  { num: 193, code: "SA", emoji: "🇸🇦", name: "サウジアラビア", nameEn: "Saudi Arabia", status: "dejure", tags: ["unique"],
    overview: "アラビア半島の大王国。イスラム教二大聖地を擁する。世界最大級の原油産出国。",
    colorRules: "Green 3425 C（暗い特定色）。1973年旗法+政府ガイダンスで法定。一般的な355 Cは不正確。",
    trivia: "シャハーダへの敬意から半旗掲揚は厳禁。両面に聖句が読めるよう鏡像の2枚布で製造される特殊構造。" },
  { num: 194, code: "SB", emoji: "🇸🇧", name: "ソロモン諸島", nameEn: "Solomon Islands", status: "defacto",
    overview: "南太平洋のメラネシア島嶼国。約1000の島。ガダルカナル島の戦いで知られる。",
    colorRules: "Blue 286 C・Yellow 116 C・Green 347 C。法定Pantone値なし。標準近似値を使用。",
    trivia: "5つの白い星は独立時の5つの主要島嶼群を象徴。黄色い対角帯で青と緑に分割される。" },
  { num: 195, code: "SC", emoji: "🇸🇨", name: "セーシェル", nameEn: "Seychelles", status: "defacto",
    overview: "インド洋西部の115島の島国。ゾウガメとココ・デ・メールで有名な生態系の宝庫。",
    colorRules: "Blue 294 C・Yellow 122 C・Red 1795 C・Green 356 C。National Symbols Act参照。全色確認済み。",
    trivia: "左下隅から放射する5本の斜帯。世界で最もカラフルな国旗の一つで5色が使われている。" },
  { num: 196, code: "SD", emoji: "🇸🇩", name: "スーダン", nameEn: "Sudan", status: "defacto",
    overview: "北東アフリカの大国。ナイル川の合流点。2011年に南スーダンが分離独立した。",
    colorRules: "Red 032 C・Green 355 C・Black C。法定Pantone値なし。汎アラブ色の標準近似値。",
    trivia: "三色帯にホイスト側の緑い三角を配する汎アラブ色旗。緑の三角は繁栄と農業を象徴。" },
  { num: 197, code: "SE", emoji: "🇸🇪", name: "スウェーデン", nameEn: "Sweden", status: "dejure",
    overview: "北欧スカンジナビア最大の国。IKEA、ABBA、ノーベル賞の国。高福祉で環境先進国。",
    colorRules: "Blue 301 C・Yellow 116 C。1982年法+1983年省令でNCS色空間により法定（De jure）。",
    trivia: "青と金の配色は中世の国章（三冠）に由来。北欧十字パターンは1906年以降も維持されている。" },
  { num: 198, code: "SG", emoji: "🇸🇬", name: "シンガポール", nameEn: "Singapore", status: "dejure",
    overview: "東南アジアの都市国家。東京23区ほどの面積に約600万人。アジア有数の金融・物流ハブ。",
    colorRules: "Red 032 C。2022年国家シンボル法でDe jure指定。",
    trivia: "三日月は若い国の成長、5星は民主・平和・進歩・正義・平等の5理想を象徴。" },
  { num: 199, code: "SH", emoji: "🇸🇭", name: "セントヘレナ", nameEn: "Saint Helena", status: "defacto",
    overview: "南大西洋の英海外領土。ナポレオンの流刑地として有名。人口は約4500人。",
    colorRules: "Blue 281 C・Red 186 C。1984年Royal Warrantで授与。ブルー・エンサイン。",
    trivia: "紋章にワイヤーバード（固有種）と帆船。2019年に鳥の正確性のため紋章が改訂された。" },
  { num: 200, code: "SI", emoji: "🇸🇮", name: "スロベニア", nameEn: "Slovenia", status: "dejure",
    overview: "中央ヨーロッパのアドリア海に面する小国。アルプス・地中海・パンノニア平原が交差。",
    colorRules: "Blue 286 C・Red 185 C。gov.siが公式CMYK値を公開。国家シンボル法に基づくDe jure。",
    trivia: "紋章はM.Pogačnik作。トリグラウ山の三峰+波線2本+ツェリェ伯の金色六芒星3個を含む。" },
  { num: 201, code: "SK", emoji: "🇸🇰", name: "スロバキア", nameEn: "Slovakia", status: "defacto",
    overview: "中央ヨーロッパの内陸国。タトラ山脈が有名。1993年チェコと平和的に分離。",
    colorRules: "Blue 286 C・Red 186 C。憲法と法63/1993号でデザインを定義。Pantone値は未規定。",
    trivia: "ロシア旗との区別のため紋章を追加。二重十字が三峰の山上に立つ赤い盾が特徴的。" },
  { num: 202, code: "SL", emoji: "🇸🇱", name: "シエラレオネ", nameEn: "Sierra Leone", status: "defacto",
    overview: "西アフリカの大西洋岸国。フリータウンは解放奴隷のために建設された首都。",
    colorRules: "Green 361 C・Blue 300 C。Album des Pavillons 1990基準。政府法定値なし。",
    trivia: "緑は天然資源と山地、白は統一と正義、青はフリータウン港と世界平和。シンプルな横三色旗。" },
  { num: 203, code: "SM", emoji: "🇸🇲", name: "サンマリノ", nameEn: "San Marino", status: "defacto",
    overview: "イタリア半島内の都市国家。世界最古の共和国（301年建国）。ティターノ山上に3つの塔。",
    colorRules: "Light Blue 2915 C。法定Pantone値なし。横二色帯（白+水色）。比率3:4。",
    trivia: "国旗版にティターノ山の3塔と「LIBERTAS（自由）」の紋章が添えられる。世界最古の共和国。" },
  { num: 204, code: "SN", emoji: "🇸🇳", name: "セネガル", nameEn: "Senegal", status: "dejure",
    overview: "西アフリカ最西端の国。旧パリ-ダカールラリーの終着点ダカール。テランガ（おもてなし）の文化。",
    colorRules: "Green 354 C・Yellow 116 C・Red 186 C。憲法がデザインを定義。3色全て標準値から修正。",
    trivia: "マリと酷似するが緑帯中央に五芒星を配する点で区別。パン・アフリカ色+イスラムの緑。" },
  { num: 205, code: "SO", emoji: "🇸🇴", name: "ソマリア", nameEn: "Somalia", status: "defacto",
    overview: "アフリカの角の東端。世界最長のアフリカ海岸線。長年の内戦と海賊問題で注目。",
    colorRules: "Light Blue 277 C。Beijing/London 2012両マニュアルで一致。国連旗の色へのオマージュ。",
    trivia: "白い五芒星の5頂点は「5つのソマリ」（ソマリア・ソマリランド・ジブチ・オガデン・北東ケニア）を象徴。" },
  { num: 206, code: "SR", emoji: "🇸🇷", name: "スリナム", nameEn: "Suriname", status: "defacto",
    overview: "南米北東部の旧オランダ植民地。アマゾン熱帯雨林が国土の90%以上。多民族共存。",
    colorRules: "Green 356 C・Red 186 C・Yellow 116 C。London 2012一致。全色確認済み。",
    trivia: "赤帯が最も太い（5帯:2:1:4:1:2比率）。黄色い五芒星は黄金の未来と全民族グループの統一。" },
  { num: 207, code: "SS", emoji: "🇸🇸", name: "南スーダン", nameEn: "South Sudan", status: "defacto",
    overview: "2011年独立の世界最年少の国家。ナイル川流域と広大な湿地帯。石油資源を有する。",
    colorRules: "Red 186 C・Blue 286 C・Yellow 116 C・Green・Black C。公式Pantone未規定でソース間乖離大。",
    trivia: "青い三角の黄色い星はベツレヘムの星（導きの光）を象徴。ケニア国旗に類似した構成。" },
  { num: 208, code: "ST", emoji: "🇸🇹", name: "サントメ・プリンシペ", nameEn: "São Tomé and Príncipe", status: "defacto",
    overview: "ギニア湾の赤道直下の島国。アフリカ最小国の一つ。高品質カカオ産地「チョコレートの島」。",
    colorRules: "Green 355 C・Yellow 116 C・Red 186 C・Black C。憲法がデザインを定義。Pantone未規定。",
    trivia: "黄帯に黒い五芒星2個はサントメ島とプリンシペ島。赤い三角は独立闘争を象徴する。" },
  { num: 209, code: "SV", emoji: "🇸🇻", name: "エルサルバドル", nameEn: "El Salvador", status: "defacto",
    overview: "中米最小の国。太平洋のみ面する中米唯一の国。火山の国でコーヒー生産国。",
    colorRules: "Blue 300 C・Yellow 116 C・Green 348 C・Black C。法定Pantone値なし。標準近似値。",
    trivia: "Bandera Magna（大旗）は189:335の独特比率。国章に5火山（中米5カ国連合）とフリジア帽。" },
  { num: 210, code: "SX", emoji: "🇸🇽", name: "シント・マールテン", nameEn: "Sint Maarten", status: "defacto",
    overview: "カリブ海セント・マーチン島南部のオランダ王国構成国。空港ビーチの飛行機ウォッチで有名。",
    colorRules: "Red 186 C・Blue 286 C。1985年採用。法定Pantone値なし。標準近似値を使用。",
    trivia: "紋章にフィリプスバーグ裁判所、蘭仏友好碑、黄セージ花束、ペリカン。多文化と友好の歴史。" },
  { num: 211, code: "SY", emoji: "🇸🇾", name: "シリア", nameEn: "Syria", status: "defacto",
    overview: "中東のレバント地域。メソポタミアとフェニキアの交差点。2011年以降内戦が続く。",
    colorRules: "Green 354 C・Red 186 C・Black C。現行は独立旗。2025年憲法改正で制定。",
    trivia: "3つの赤い五芒星はかつてのアラブ連合共和国（エジプト・シリア・イラク）を象徴していた。" },
  { num: 212, code: "SZ", emoji: "🇸🇿", name: "エスワティニ", nameEn: "Eswatini", status: "defacto",
    overview: "南部アフリカの内陸国。2018年にスワジランドから改名。アフリカ最後の絶対君主制。",
    colorRules: "5帯構成（青黄赤黄青）。ソース間で色の変動が非常に大きい。データは新規作成。",
    trivia: "中央赤帯にンクニ牛革の盾と杖（インジョボ羽飾り付き）と交差する2本の槍。スワジ戦士の伝統装備。" },
  { num: 213, code: "TC", emoji: "🇹🇨", name: "タークス・カイコス", nameEn: "Turks and Caicos", status: "defacto",
    overview: "カリブ海のイギリス海外領土。約40の島。世界有数のダイビングスポットとタックスヘイブン。",
    colorRules: "Blue 281 C・Yellow 116 C・Green 348 C。英ブルー・エンサイン。法定Pantone規定なし。",
    trivia: "紋章に巻き貝、フラミンゴ、ターキーヘッド・サボテン。カリブの固有生態系を象徴的に描く。" },
  { num: 214, code: "TD", emoji: "🇹🇩", name: "チャド", nameEn: "Chad", status: "dejure",
    overview: "中部アフリカの内陸国。サハラ砂漠とサヘル地帯にまたがる。チャド湖は縮小中。",
    colorRules: "Blue 281 C・Yellow 116 C・Red 186 C。1962年憲法でDe jure指定。全色確認済み。",
    trivia: "ルーマニア国旗とほぼ同一。チャドの青がより暗い藍色（281 vs 280）。国連にも異議が申し立てられた。" },
  { num: 215, code: "TG", emoji: "🇹🇬", name: "トーゴ", nameEn: "Togo", status: "defacto", tags: ["unique"],
    overview: "西アフリカの細長い国。リン鉱石の産出で知られる。首都ロメは商業の中心。",
    colorRules: "Green 354 C・Yellow 116 C・Red 186 C。法定Pantone値なし。3色すべて修正済み。",
    trivia: "比率は黄金比（1:φ≈1:1.618）を採用する世界で唯一の国旗。実務的には3:5も使用する。" },
  { num: 216, code: "TH", emoji: "🇹🇭", name: "タイ", nameEn: "Thailand", status: "dejure",
    overview: "東南アジアの王国。唯一欧州植民地化を免れた国。仏教文化、タイ料理、ムエタイで著名。",
    colorRules: "Red 186 C・Blue 281 C。1917年勅令→1979年法→2017年CIELAB D65標準。世界的に珍しい色空間法定化。",
    trivia: "5帯の「トング・トライロング」。中央の藍帯はラーマ6世の金曜日の吉色（タイでは青色の日）。" },
  { num: 217, code: "TJ", emoji: "🇹🇯", name: "タジキスタン", nameEn: "Tajikistan", status: "defacto",
    overview: "中央アジアの山岳国。国土の93%が山地。パミール高原は「世界の屋根」。旧ソ連構成国。",
    colorRules: "Red 192 C・Green 348 C・Yellow 115 C。法定Pantone値なし。帯幅比2:3:2。",
    trivia: "金冠と七星アーチ。7つの星は「タージ（冠）」と7（完全性を示す聖なる数）を象徴する。" },
  { num: 218, code: "TK", emoji: "🇹🇰", name: "トケラウ", nameEn: "Tokelau", status: "defacto",
    overview: "南太平洋のNZ依存領域。3つの環礁島。人口約1500人。電力は100%太陽光発電。",
    colorRules: "Blue 280 C・Yellow 109 C。2009年Royal Warrantで採用。Blazon: Azure, Canoe Or。",
    trivia: "旗にはホイスト方向へ航行するカヌー（va'a）と南十字星。航海モチーフがポリネシア文化を反映。" },
  { num: 219, code: "TL", emoji: "🇹🇱", name: "東ティモール", nameEn: "Timor-Leste", status: "dejure",
    overview: "東南アジアのティモール島東半分。2002年にインドネシアから独立した21世紀最初の独立国。",
    colorRules: "Red 485 C・Yellow 123 C・Black C。憲法第15条でDe jure指定。2つの重なる三角形デザイン。",
    trivia: "赤は独立闘争の犠牲、黒は植民地時代の暗黒、黄は植民地支配の痕跡、白い星は希望の光。" },
  { num: 220, code: "TM", emoji: "🇹🇲", name: "トルクメニスタン", nameEn: "Turkmenistan", status: "defacto", tags: ["unique"],
    overview: "中央アジアの永世中立国。カラクム砂漠が国土の約70%。天然ガス埋蔵量は世界第4位。",
    colorRules: "Green 348 C・Red 187 C・Yellow 123 C。大統領令PP-3051参照。Pantone値は未法定。",
    trivia: "世界で最も複雑な国旗の一つ。赤帯に5つの絨毯グル（5部族の伝統模様）が描かれる精緻な意匠。" },
  { num: 221, code: "TN", emoji: "🇹🇳", name: "チュニジア", nameEn: "Tunisia", status: "dejure",
    overview: "北アフリカのマグレブ地域。古代カルタゴの遺跡。2010年ジャスミン革命でアラブの春の先駆け。",
    colorRules: "Red 186 C。法99-56号で精密な幾何学構築規則を提供（De jure）。白円盤直径=旗長の1/3。",
    trivia: "オスマン帝国の影響を受けた意匠で1831年に制定された長い歴史を持つ旗。三日月と五芒星を配する。" },
  { num: 222, code: "TO", emoji: "🇹🇴", name: "トンガ", nameEn: "Tonga", status: "dejure",
    overview: "南太平洋の王国。ポリネシア唯一の君主制国家。約170の島。ラグビーとホエールウォッチング。",
    colorRules: "Red 186 C。1875年憲法§47でDe jure指定。Album des Pavillons 2023基準。",
    trivia: "憲法に「ジョージ王の旗は決して変更されない」と明記。世界で最も変更が困難な国旗。" },
  { num: 223, code: "TR", emoji: "🇹🇷", name: "トルコ", nameEn: "Türkiye", status: "dejure",
    overview: "ヨーロッパとアジアにまたがる国。ビザンチン・オスマンの遺産とイスラム文化。NATOの東の要。",
    colorRules: "Red 186 C（HEX #E30A17）。法2893号+TSE製造基準でDe jure。幾何学構築法も法定。",
    trivia: "三日月と星は厳密な数学的規則で配置。三日月外円直径=旗幅の1/2、内円=0.4G、星円=1/4G。" },
  { num: 224, code: "TT", emoji: "🇹🇹", name: "トリニダード・トバゴ", nameEn: "Trinidad and Tobago", status: "defacto",
    overview: "カリブ海最南端の島国。カーニバルとスチールパン発祥の地。石油・天然ガスが経済の柱。",
    colorRules: "Red 186 C・Black C。法定Pantone値なし。比率3:5。白縁黒斜帯（旗長の1/5幅）。",
    trivia: "白い縁付き黒帯は大地と統一。赤は太陽と国民の活力、白は海と平等、黒は忍耐と強さ。" },
  { num: 225, code: "TV", emoji: "🇹🇻", name: "ツバル", nameEn: "Tuvalu", status: "defacto",
    overview: "南太平洋の世界第4位の小国。9つの環礁島。気候変動による海面上昇で存亡の危機。",
    colorRules: "Light Blue 279 C・Blue 280 C・Red 186 C・Yellow 116 C。全色確認済み。",
    trivia: "9つの黄色い星は9島の地理的配置を正確に反映。1995-97年の別旗は不評で元の旗に復帰。" },
  { num: 226, code: "TW", emoji: "🇹🇼", name: "台湾", nameEn: "Taiwan", status: "dejure",
    overview: "東アジアの島嶼政体。半導体産業で世界的に重要。民主主義と経済発展を両立させた「アジアの虎」。",
    colorRules: "Red 2347 C・Blue 2738 C。中華民國國徽國旗法（1928年）でDe jure。内政部がCMYK参照値を提供。",
    trivia: "「青天白日滿地紅」。12光条の太陽は12時間を象徴し各30°間隔。1928年以来のデザインが維持。" },
  { num: 227, code: "TZ", emoji: "🇹🇿", name: "タンザニア", nameEn: "Tanzania", status: "defacto",
    overview: "東アフリカの国。キリマンジャロ山、セレンゲティ国立公園、ザンジバル島で有名。",
    colorRules: "Green 361 C・Yellow 116 C・Blue 299 C・Black C。全色確認済み。標準近似値を使用。",
    trivia: "タンガニーカとザンジバルの連合旗。対角黒帯（黄縁）が走るダイナミックなデザイン。" },
  { num: 228, code: "UA", emoji: "🇺🇦", name: "ウクライナ", nameEn: "Ukraine", status: "dejure",
    overview: "東ヨーロッパの国。欧州第2位の面積。肥沃な黒土地帯「欧州のパンかご」。",
    colorRules: "Blue 2935 C・Yellow 012 C。DSTU 4512:2006（国家技術標準）でDe jure指定。",
    trivia: "青は空、黄は小麦畑を象徴。配色は13世紀のルーシ公国の紋章に遡り欧州最古級の配色の一つ。" },
  { num: 229, code: "UG", emoji: "🇺🇬", name: "ウガンダ", nameEn: "Uganda", status: "defacto",
    overview: "東アフリカの内陸国。ヴィクトリア湖に面する「アフリカの真珠」。マウンテンゴリラで有名。",
    colorRules: "Yellow 116 C・Red 186 C・Black C・Grey 430 C。法定Pantone値なし。標準近似値。",
    trivia: "中央の白い円盤にハイイロカンムリヅル。この鶴は優雅で穏やかな国民性を象徴する国鳥。" },
  { num: 230, code: "US", emoji: "🇺🇸", name: "アメリカ合衆国", nameEn: "United States", status: "dejure",
    overview: "北米の超大国。50州からなる連邦共和国。世界最大の経済力と軍事力を持つ。",
    colorRules: "Old Glory Red 193 C・Old Glory Blue 281 C。EO 10834(1959)でDe jure。比率10:19。",
    trivia: "50星は50州、13縞は独立時の13植民地。1908年以降、オリンピックで他国に旗を下げない伝統がある。" },
  { num: 231, code: "UY", emoji: "🇺🇾", name: "ウルグアイ", nameEn: "Uruguay", status: "defacto",
    overview: "南米のラプラタ川河口の小国。牧畜と農業が主要産業。1930年初のW杯開催国。",
    colorRules: "Blue Reflex Blue C・Yellow 116 C・Brown 731 C。法定Pantone値なし。9帯（白5+青4）。",
    trivia: "白カントンの「五月の太陽」はアルゼンチン国旗と同じインカの太陽神に由来。顔付きの太陽が特徴。" },
  { num: 232, code: "UZ", emoji: "🇺🇿", name: "ウズベキスタン", nameEn: "Uzbekistan", status: "defacto",
    overview: "中央アジアの二重内陸国。シルクロードの歴史的都市が世界遺産。綿花の大産出国。",
    colorRules: "Blue 285 C・Red 485 C・Green 361 C。公式Pantone未規定。標準近似値を維持。",
    trivia: "三日月はイスラムの新生、12の白い星は12の州（viloyat）を表す。赤帯は生命力を象徴。" },
  { num: 233, code: "VA", emoji: "🇻🇦", name: "バチカン市国", nameEn: "Vatican City", status: "defacto", tags: ["square"],
    overview: "世界最小の独立国家。ローマ市内のカトリック教会の総本山。教皇が元首。",
    colorRules: "Yellow 116 C・Red 186 C。Album des Pavillons準拠。旧値803 C（蛍光色）は誤りとして修正。",
    trivia: "スイスと並ぶ世界唯2の正方形国旗。紋章の2つの鍵は聖ペトロの天国と地上の鍵を象徴。" },
  { num: 234, code: "VC", emoji: "🇻🇨", name: "セントビンセント", nameEn: "Saint Vincent", status: "defacto",
    overview: "カリブ海東部の島国。32の島。ラ・スフリエール火山とセーリングリゾートで有名。",
    colorRules: "Blue 286 C・Yellow 116 C・Green 354 C。法定Pantone値なし。標準近似値を使用。",
    trivia: "黄帯の3つのV字形ダイヤモンドは「カリブの宝石」の愛称を表す。帯幅比1:2:1。" },
  { num: 235, code: "VE", emoji: "🇻🇪", name: "ベネズエラ", nameEn: "Venezuela", status: "dejure",
    overview: "南米北部のカリブ海沿岸国。世界最大の確認石油埋蔵量。エンジェルフォールがある。",
    colorRules: "Yellow 116 C・Blue 286 C・Red 186 C。2006年法でDe jure。3色すべて以前の値から修正。",
    trivia: "2006年改正で8番目の星を追加。ボリバルの1817年勅令に基づき解放された8州を象徴。" },
  { num: 236, code: "VG", emoji: "🇻🇬", name: "英領バージン諸島", nameEn: "British Virgin Islands", status: "defacto",
    overview: "カリブ海の英海外領土。約50の島。セーリングと金融のパラダイス。",
    colorRules: "Blue 281 C・Red 186 C・Yellow 116 C・Green 363 C。英ブルー・エンサイン。法定値なし。",
    trivia: "紋章の聖ウルスラは11の炎ランプを伴う。島名はコロンブスが処女殉教者伝説から命名。" },
  { num: 237, code: "VI", emoji: "🇻🇮", name: "米領バージン諸島", nameEn: "US Virgin Islands", status: "defacto",
    overview: "カリブ海のアメリカ準州。主要3島。観光とラム酒が産業の柱。",
    colorRules: "Yellow 102 C・Blue 281 C・Green 355 C・Red 179 C。1921年EO採用。London 2012基準。",
    trivia: "白地にアメリカン・イーグルが月桂枝と3本の青矢を持つ。胸の盾は星条旗のストライプ。" },
  { num: 238, code: "VN", emoji: "🇻🇳", name: "ベトナム", nameEn: "Viet Nam", status: "dejure",
    overview: "東南アジアのインドシナ半島東部。S字型の国土。フォー、アオザイ、ハロン湾で世界に知られる。",
    colorRules: "Red 186 C・Yellow 116 C。憲法Art.141でDe jure：「鮮紅色地に金色の五芒星」。",
    trivia: "星の5頂点は知識人・農民・労働者・起業家・軍人の5階層。半径は旗長の1/5と憲法で規定。" },
  { num: 239, code: "VU", emoji: "🇻🇺", name: "バヌアツ", nameEn: "Vanuatu", status: "defacto",
    overview: "南太平洋のメラネシア島嶼国。約80の島。活火山、バンジージャンプの起源（ナゴール）で有名。",
    colorRules: "Red 186 C・Green 347 C・Yellow 116 C・Black C。全色確認済み。比率3:5。",
    trivia: "黒三角内の猪の牙は繁栄の象徴。交差するナメレ・シダの39葉は39人の議員を表す。" },
  { num: 240, code: "WF", emoji: "🇼🇫", name: "ウォリス・フツナ", nameEn: "Wallis and Futuna", status: "defacto",
    overview: "南太平洋のフランス海外準県。3つの王国が伝統的統治を維持。人口約1万1千人。",
    colorRules: "Red 186 C・Blue 286 C。公式旗はフランス三色旗。非公式地元旗にPantone法的地位なし。",
    trivia: "非公式ウヴェア旗は赤地に仏三色旗カントン+白い十字パテ。4白三角は3人の王と仏総督を表す。" },
  { num: 241, code: "WS", emoji: "🇼🇸", name: "サモア", nameEn: "Samoa", status: "defacto",
    overview: "南太平洋のポリネシア島国。ポリネシア最古の独立国（1962年）。ラグビーが国民的スポーツ。",
    colorRules: "Red 186 C・Blue 281 C。Act 1994はデザインのみ規定。Pantone未指定。標準近似値を使用。",
    trivia: "青カントンに白い南十字星5星。当初は4星だったが1949年に5に変更。赤は勇気、白は純潔、青は太平洋。" },
  { num: 242, code: "XK", emoji: "🇽🇰", name: "コソボ", nameEn: "Kosovo", status: "defacto",
    overview: "バルカン半島中部の国。2008年独立宣言。国連未加盟だが100以上の国が承認。",
    colorRules: "Blue 2133 C・Gold 7407 C。法定Pantone値なし。複数ソースで一致。比率5:7。",
    trivia: "ボスニアと同様にEU旗にインスピレーションを受けた意匠。6白星は6民族の平等を象徴。" },
  { num: 243, code: "YE", emoji: "🇾🇪", name: "イエメン", nameEn: "Yemen", status: "defacto",
    overview: "アラビア半島南端の国。シバ王国の歴史を持つ。1990年の南北統一後、内戦状態が続く。",
    colorRules: "Red 186 C・Black C。1990年統一で採用。法定Pantone値なし。汎アラブ色の三等分帯。",
    trivia: "赤は革命、白は明るい未来、黒は暗い過去を象徴する汎アラブの伝統。リビア・エジプトの旗の変形。" },
  { num: 244, code: "YT", emoji: "🇾🇹", name: "マヨット", nameEn: "Mayotte", status: "dejure",
    overview: "インド洋コモロ諸島内のフランス海外県。2011年に県に昇格。世界最大のラグーンの一つ。",
    colorRules: "Blue 072 C・Red 485 C。AFNOR NFX 08002準拠のフランス三色旗。De jure指定。",
    trivia: "非公式旗の紋章に三日月、イランイランの花、タツノオトシゴ、モットー「RA HACHIRI」が描かれる。" },
  { num: 245, code: "ZA", emoji: "🇿🇦", name: "南アフリカ", nameEn: "South Africa", status: "dejure",
    overview: "アフリカ大陸最南端の国。「虹の国」と称される多民族国家。金・ダイヤモンドの産地。",
    colorRules: "Green 3415 C・Black C・Yellow 1235 C・Red 179 C・Blue Reflex Blue C。SABS CKS繊維色コード法定。",
    trivia: "1994年アパルトヘイト廃止後に採用。Y字のパルは多様な人々の統合と新たな道を象徴する6色旗。" },
  { num: 246, code: "ZM", emoji: "🇿🇲", name: "ザンビア", nameEn: "Zambia", status: "dejure",
    overview: "南部アフリカの内陸国。ヴィクトリアの滝で世界的に有名。銅の主要産出国。",
    colorRules: "Green BCC 100・Red 186 C・Black C・Orange 151 C。National Flag Act+BCC色番号で法定。",
    trivia: "右下の三色帯上にアフリカン・フィッシュ・イーグルが飛翔。鷲は自由と困難克服の力を象徴。" },
  { num: 247, code: "ZW", emoji: "🇿🇼", name: "ジンバブエ", nameEn: "Zimbabwe", status: "defacto",
    overview: "南部アフリカの内陸国。大ジンバブエ遺跡が国名の由来。ヴィクトリアの滝をザンビアと共有。",
    colorRules: "Green 355 C・Yellow 116 C・Red 186 C・Black C。法定Pantone値なし。7帯構成。",
    trivia: "白い三角の中にジンバブエ・バード。大ジンバブエ遺跡発掘の石彫で国の硬貨にも使われる象徴。" },
];

// ── Fun Facts Data ────────────────────────────────
const FUN_FACTS = [
  { icon: "🏳️", number: "250", label: "カ国・地域を収録" },
  { icon: "🏛️", number: "~80", label: "カ国が法定根拠あり（De Jure）" },
  { icon: "⬜", number: "2", label: "正方形の国旗（スイス＆バチカン）" },
  { icon: "📐", number: "1", label: "非長方形の国旗（ネパール🇳🇵）" },
  { icon: "🔫", number: "1", label: "近代火器が描かれた国旗（モザンビーク🇲🇿）" },
  { icon: "🔄", number: "1", label: "表裏異デザインの国旗（パラグアイ🇵🇾）" },
  { icon: "📏", number: "11:28", label: "最も横長い比率（カタール🇶🇦）" },
  { icon: "🎨", number: "6", label: "最多色数の国旗（南アフリカ🇿🇦）" },
  { icon: "📜", number: "1219", label: "世界最古の現役国旗（デンマーク🇩🇰）" },
  { icon: "🌀", number: "φ", label: "黄金比を採用する唯一の国旗（トーゴ🇹🇬）" },
  { icon: "🏴‍☠️", number: "~25", label: "回以上国旗変更（アフガニスタン🇦🇫）" },
  { icon: "🇫🇷", number: "~10", label: "地域がフランス三色旗を公式旗に使用" },
];

// ── State ─────────────────────────────────────────
let searchQuery = '';
let activeFilter = 'all';
let expandedCards = new Set();

// ── Initialize ────────────────────────────────────
function init() {
  renderGrid();
  renderFunFacts();
  updateStats();
  setupEventListeners();
  createScrollToTop();
}

function updateStats() {
  const dejure = GUIDE_DATA.filter(d => d.status === 'dejure').length;
  const defacto = GUIDE_DATA.filter(d => d.status === 'defacto').length;
  document.getElementById('stat-dejure').textContent = dejure;
  document.getElementById('stat-defacto').textContent = defacto;
}

// ── Render Grid ───────────────────────────────────
function renderGrid() {
  const grid = document.getElementById('guide-grid');
  const filtered = getFilteredData();

  if (filtered.length === 0) {
    grid.innerHTML = `
      <div class="guide-no-results">
        <div class="icon">🔍</div>
        <p>該当する国旗が見つかりません</p>
      </div>`;
    return;
  }

  grid.innerHTML = filtered.map(d => {
    const isExpanded = expandedCards.has(d.code);
    const statusBadge = d.status === 'dejure'
      ? '<span class="card-dejure-badge">De Jure</span>'
      : '<span class="card-defacto-badge">De Facto</span>';

    return `
      <div class="country-card ${isExpanded ? 'expanded' : ''}" id="card-${d.code}">
        <div class="card-header" onclick="toggleCard('${d.code}')">
          <div class="card-flag-wrap">
            <img src="03_svg_verified/${d.code}.svg?v=20260415c" alt="${d.nameEn}" loading="lazy"
                 onerror="this.src='01_svg_wikipedia/${d.code}.svg?v=20260415c'; this.onerror=function(){this.src='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22120%22 height=%2280%22><rect fill=%22%23333%22 width=%22120%22 height=%2280%22/><text x=%2260%22 y=%2244%22 text-anchor=%22middle%22 fill=%22%23666%22 font-size=%2212%22>${d.code}</text></svg>';}" >
          </div>
          <div class="card-title-area">
            <div class="card-number">#${String(d.num).padStart(3, '0')} <span class="card-code-badge">${d.code}</span> ${statusBadge}</div>
            <div class="card-country-name">
              <span class="emoji">${d.emoji}</span> ${d.name}
              <span style="color:var(--text-muted);font-weight:400;font-size:0.78rem">${d.nameEn}</span>
            </div>
          </div>
          <button class="card-toggle" aria-label="展開">▼</button>
        </div>
        <div class="card-body">
          <div class="card-body-inner">
            <div class="info-sections">
              <div class="info-block overview">
                <div class="info-block-label"><span class="label-icon">🌍</span> 国の概要</div>
                <div class="info-block-text">${d.overview}</div>
              </div>
              <div class="info-block color-rules">
                <div class="info-block-label"><span class="label-icon">🎨</span> 色のルール</div>
                <div class="info-block-text">${d.colorRules}</div>
              </div>
              <div class="info-block trivia">
                <div class="info-block-label"><span class="label-icon">💡</span> トリビア</div>
                <div class="info-block-text">${d.trivia}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    `;
  }).join('');
}

// ── Filter Logic ──────────────────────────────────
function getFilteredData() {
  return GUIDE_DATA.filter(d => {
    // Filter
    if (activeFilter === 'dejure' && d.status !== 'dejure') return false;
    if (activeFilter === 'defacto' && d.status !== 'defacto') return false;
    if (activeFilter === 'square' && (!d.tags || !d.tags.includes('square'))) return false;
    if (activeFilter === 'unique' && (!d.tags || !d.tags.includes('unique'))) return false;
    // Search
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      return d.name.includes(searchQuery)
        || d.nameEn.toLowerCase().includes(q)
        || d.code.toLowerCase().includes(q)
        || d.overview.includes(searchQuery)
        || d.colorRules.includes(searchQuery)
        || d.trivia.includes(searchQuery);
    }
    return true;
  });
}

// ── Card Toggle ───────────────────────────────────
function toggleCard(code) {
  if (expandedCards.has(code)) {
    expandedCards.delete(code);
  } else {
    expandedCards.add(code);
  }
  const card = document.getElementById(`card-${code}`);
  if (card) card.classList.toggle('expanded');
}

// ── Fun Facts ─────────────────────────────────────
function renderFunFacts() {
  document.getElementById('facts-grid').innerHTML = FUN_FACTS.map(f => `
    <div class="fact-card">
      <span class="fact-icon">${f.icon}</span>
      <div class="fact-number">${f.number}</div>
      <div class="fact-label">${f.label}</div>
    </div>
  `).join('');
}

// ── Scroll To Top ─────────────────────────────────
function createScrollToTop() {
  const btn = document.createElement('button');
  btn.className = 'scroll-top-btn';
  btn.innerHTML = '↑';
  btn.title = 'トップへ戻る';
  btn.onclick = () => window.scrollTo({ top: 0, behavior: 'smooth' });
  document.body.appendChild(btn);

  window.addEventListener('scroll', () => {
    btn.classList.toggle('visible', window.scrollY > 600);
  });
}

// ── Event Listeners ───────────────────────────────
function setupEventListeners() {
  // Search
  document.getElementById('search').addEventListener('input', e => {
    searchQuery = e.target.value;
    renderGrid();
  });

  // Filters
  document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      activeFilter = btn.dataset.filter;
      renderGrid();
    });
  });
}

// ── Boot ──────────────────────────────────────────
document.addEventListener('DOMContentLoaded', init);
